### PR TITLE
Remove `Style/DateTime` cop

### PR DESCRIPTION
**Pull request by AlexWayfer**
1. It doesn't resolve original described problem: https://github.com/rubocop-hq/rubocop/issues/1952#issuecomment-337825607
2. `Time#to_s` is not ISO6801 compliant by default: https://github.com/rubocop-hq/rubocop/issues/1952#issuecomment-360470787
3. `Time.parse` works wrong with timezones: https://github.com/rubocop-hq/rubocop/issues/1952#issuecomment-411350426

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bdewater** [comment]
Regardless of the discussion which is more correct in #1952 - I feel we should have a cop that enforces the good one. Mixing them has been a source of bugs for me in the past so I'm 👎on removal.

**Comment by AlexWayfer** [comment]
> Mixing them has been a source of bugs for me in the past

Examples, please (you can write them in issue, yes).

**Comment by deivid-rodriguez** [comment]
I'm :-1: on removal too. Their behaviour seems to be slightly different, but most apps probably won't care. So choosing one over the other for consistency seems like a good idea to me. "Disabled by default" seems like a good compromise.

**Comment by AlexWayfer** [comment]
> Their behaviour seems to be slightly different, but most apps probably won't care.

So, why is there this cop then?

> So choosing one over the other for consistency seems like a good idea to me.

Why is `DateTime` "bad"? Why not `Time`?

**Comment by deivid-rodriguez** [comment]
> > Their behaviour seems to be slightly different, but most apps probably won't care.

> So, why is there this cop then?

Sorry, I failed to explain what I meant. I meant most apps won't need features specific to one class or the other, and could work with any of them. But they _will_ probably care about one or the other being used consistenly if they use rubocop.

> Why is DateTime "bad"? Why not Time?

Mmm, in [the docs about this](https://ruby-doc.org/stdlib-2.5.1/libdoc/date/rdoc/DateTime.html#class-DateTime-label-When+should+you+use+DateTime+and+when+should+you+use+Time-3F),  it doesn't really explain _why_ `Time` is preferred when you're dealing with current times and not historiaI dates / calendars. But my guess is that `Time` is faster since it's a "pure" class (implemented in C), and not a ruby construction on top of `Date` that most people won't need. Not sure though...

Maybe there's an argument to add a new style to the cop that prefers `DateTime`, but fully removing the cop seems like a no-go. You can get the same effect by disabling the cop and without making everybody else also losing it.

From the 3 issues you mention in this PR description, the first one seems like a bug in `rubocop`. The other two seem like things that could be improved upstream, and if that's not possible, a valid motivation to add the opposite style to the cop.

**Comment by AlexWayfer** [comment]
> You can get the same effect by disabling the cop and without making everybody else also losing it.

I want to understand reasons for this cop and put the point.

I don't consider that described reasons before this cop adding are OK. I described in the issue why.

I didn't see OK answers for my questions in the closed issue before this PR. These answers were in favor of `DateTime` or didn't work at all.

> The other two seem like things that could be improved upstream, and if that's not possible, a valid motivation to add the opposite style to the cop.

Let's drop this cop until they're fixed ("improved").

**Comment by deivid-rodriguez** [comment]
For example, you mention https://github.com/rubocop-hq/rubocop/issues/1952#issuecomment-337825607 in the first bullet point but I don't get any offenses on that code (as expected, because it uses historical dates).

Regarding the other two issues, these are different classes that work slightly differently. And alternatives have been mentioned to keep the same behavior. For example, quoting @bdewater regarding the ISO6801 formatting:

> I meant that if you feel Time#to_s should output ISO8601 formatted data, that could be fixed upstream. I don't think it's much of a reason for debating the existence of this cop, because Time#iso8601 is available.

If you still don't like the alternatives, or they don't work for you, you can still disable the cop, or propose a style that prefers `DateTime` over `Time`.

**Comment by AlexWayfer** [comment]
> Regarding the other two issues, these are different classes that work slightly differently.

So I don't see a reason block one of them in favor of another, if the first (`DateTime`) doesn't bad, just different.

**Comment by bbatsov** [comment]
If I recall correctly the cop was inspired by this article https://gist.github.com/pixeltrix/e2298822dd89d854444b

**Comment by AlexWayfer** [comment]
> If I recall correctly the cop was inspired by this article https://gist.github.com/pixeltrix/e2298822dd89d854444b

Please, read the first bullet from the description of this PR.

**Comment by deivid-rodriguez** [comment]
> So I don't see a reason to block one of them in favor of another, if the first (DateTime) doesn't bad, just different.

I like the consistency, and that we put less cognitive load on new developers that don't need to learn to classes and try to find out why one was chosen over the other (and reach to no conclusion most of the times). Anyways, I think disabling the cop is perfect for your case!

> If I recall correctly the cop was inspired by this article https://gist.github.com/pixeltrix/e2298822dd89d854444b

Indeed, and I only now found out that article made it to the official ruby docs: https://ruby-doc.org/stdlib-2.5.1/libdoc/date/rdoc/DateTime.html#class-DateTime-label-When+should+you+use+DateTime+and+when+should+you+use+Time-3F.

**Comment by AlexWayfer** [comment]
> @AlexWayfer I think there's enough information in previous posts already for the ones who make the decisions to decide here. 

I think no. I still don't see the arguments for `Time` instead of `DateTime`. Consistency? So why is there `Date` recommendation? `Time` has date. Let's offense any similar things without obvious reasons.

> So I'd rather not continue this discussion since I don't think we're bringing anything new to the table.

I want to bring **the lack of arguments, reasons** for this cop. If somebody can describe why `DateTime` is really bad — OK, let's leave this cop and I'll switch to `Time`. 

For now I see: "Oh, we have some optional parameter for a Julian day number, which give us the strange but correct results about dates in 1616, so you'll want to use Time since your app is probably dealing with current dates and times. But you can make mistakes as UNESCO with Time class for these dates".

What? If I don't care about 1616 — why should I use `Time` if `DateTime` make its work good with current dates? If I do — I have to use `DateTime` instead of `Time`.

Why are you suggesting `Time` instead of `DateTime` with links to this article and copy-pasted documentation without arguments for this decision. I don't like this approach. I'll suggest to remove any unwarranted cop.

**Comment by bbatsov** [comment]
> Please, read the first bullet from the description of this PR.

Ah, sorry about this. Didn't notice you already found this. I've been extremely busy lately and didn't pay enough attention to the conversation here so far. Maybe we really didn't have a solid rationale for creating this cop to begin with. 

> Why are you suggesting Time instead of DateTime with links to this article and copy-pasted documentation without arguments for this decision. I don't like this approach. I'll suggest to remove any unwarranted cop.

Yeah, I concur. Without any substance to this decision it feels pretty random (especially if it's not possible to always use `Time` instead of `DateTime`). I'd like to do some more research to make sure there wasn't something I forget about this, but I'm generally in favour of removing (or rather disabling and updating its description) this.

Give me some time to be able to carefully go through the conversation. In the mean time I'd like to hear what @koic, @jonas054, @Drenmi and @Darhazer think about this.

**Comment by AlexWayfer** [comment]
> Yeah, I concur. Without any substance to this decision it feels pretty random (especially if it's not possible to always use Time instead of DateTime). I'd like to do some more research to make sure there wasn't something I forget about this, but I'm generally in favour of removing (or rather disabling and updating its description) this.
> 
> Give me some time to be able to carefully go through the conversation. In the mean time I'd like to hear what @koic, @jonas054, @Drenmi and @Darhazer think about this.

Yeah, sure, thank you.

**Comment by deivid-rodriguez** [comment]
@bbatsov Thanks for your input.

I must say that I wasn't aware that the statement "it's not possible to always use Time instead of DateTime" could actually be true when not dealing with historical dates. Clearly I don't see bullet points 1 and 2 in this PR proving it, but regarding the third point, I just tried the examples @AlexWayfer mentioned in https://github.com/rubocop-hq/rubocop/issues/1952#issuecomment-414236002, and I get the same results he's getting regarding dst... Perhaps we could respectfully ping @pixeltrix as the author of that article that ended up making it into the official docs. :)

There's something I definitely think the cop is doing wrong. `Date` should not be recommended in general as an alternative to `DateTime` or `Time`, since it has no time information at all! I think we should fix that if the cop ends up staying.

**Comment by deivid-rodriguez** [comment]
If we end up agreeing that `DateTime` is better when dealing with timezones, would a cop that enforces usage of `DateTime` in our code, instead of mixed usage, be interesting? Or if you have an app that does not need to deal with timezones at all, would a cop that enforces consistent usage of either `DateTime` or `Time` across the application be interesting? These are the cases I like this cop to deal with, not the fact that one class is superior to the other.

**Comment by AlexWayfer** [comment]
> Clearly I don't see bullet points 1 and 2 in this PR proving it, but regarding the third point, I just tried the examples @AlexWayfer mentioned in #1952 (comment), and I get the same results he's getting regarding dst... Perhaps we could respectfully ping @pixeltrix as the author of that article that ended up making it into the official docs. :)

The first bullet point is addressed to original article. I don't see a reason why `DateTime` is bad in the described examples.

> If we end up agreeing that DateTime is better when dealing with timezones, would a cop that enforces usage of DateTime in our code, instead of mixed usage, be interesting?

I don't think that `DateTime` is better than `Time` with timezones. I think they're almost equal in this question. And I don't know for now how to check this. I just don't accept cops without clear facts and reproducible examples.

**Comment by deivid-rodriguez** [comment]
In this first bullet point, you link to a comment where you claim that some code produces a rubocop warning, but it does not produce such a warning for me... :thinking:

> I don't think that DateTime is better than Time with timezones. I think they're almost equal in this question. And I don't know for now how to check this.

Ok, so in your opinion, if your code needs to deal with timezones, each of this classes has valid usages and it's impossible to check when to use which. That (if true) makes sense to me. What about code bases that don't need to deal with timezones. Would a cop to enforce one class or the other make sense? If you think this makes sense, maybe keeping this cop disabled by default (so this kind of apps could still opt-in) could be a reasonable path to take?

>  I just don't accept cops without clear facts and reproducible examples.

Remember that this is a style cop. Style cops are meant to enforce consistent and uniform style.

**Comment by AlexWayfer** [comment]
> In this first bullet point, you link to a comment where you claim that some code produces a rubocop warning, but it does not produce such a warning for me...

Yeah, sorry, it's not complete correct comment. I just tried to find where is `Date` is better than `DateTime`.

> What about code bases that don't need to deal with timezones. Would a cop to enforce one class or the other make sense?

I don't know if you should use `Time` or `DateTime` at all. Maybe it should be `String`. Or you should use something like `Time.new(year, month, day, ...)`, and then there is no difference between `Time` and `DateTime` I guess.

**Comment by deivid-rodriguez** [comment]
> Yeah, sorry, it's not complete correct comment. I just tried to find where is Date is better than DateTime.

Yeah, I agree this cop should not recommend `Date`. :+1:

>  don't know if you should use Time or DateTime at all. Maybe it should be String. Or you should use something like Time.new(year, month, day, ...), and then there is no difference between Time and DateTime I guess.

>  don't know if you should use Time or DateTime at all. Maybe it should be String

I don't think `String` is good to deal with dates and times that don't need to deal with time zones. I'd be missing date(time) comparison, localization, date(time) arithmetics...

> , and then there is no difference between Time and DateTime I guess.

So you'd agree with having such a style cop for those cases, disabled by default?

**Comment by AlexWayfer** [comment]
> Remember that this is a style cop. Style cops are meant to enforce consistent and uniform style.

OK, but I don't understand: we have Style cops about characters, one-liners, brackets, methods, parameters… But `Time` and `DateTime` are classes, different classes!

> So you'd agree with having such a style cop for those cases, disabled by default?

Why? Who can want to enable it and for what if there is no difference between `Time` and `DateTime`?

If you want a consistency — OK, maybe there is should be disabled cop with different styles. But… we even don't know for what cases `Time` or `DateTime` is better than another. And those different cases can be faced in the one project. You see cop "Use `DateTime` instead of `Time`", for example, you think "OK, I'll", but you're writing a code for which `Time` is better.

Let's figure the difference out before adding any cop with enforcing one class in favor of another. Or just don't think about it and don't add such cop.

**Comment by deivid-rodriguez** [comment]
> OK, but I don't understand: we have Style cops about characters, one-liners, brackets, methods, parameters… But Time and DateTime are classes, different classes!

Different but highly overlapping. This seems to be the only case in the standard library where something like this happens, so it makes sense to me that it's the only style cop normalizing class usage.

> Why? Who can want to enable it and for what if there is no difference between Time and DateTime?

Not sure what you're saying here, but you seem to be asking why would someone enable a style cop?

> Let's figure the difference out before adding any cop with enforcing one class in favor of another. Or just don't think about it and don't add such cop.

You're talking as if this PR was already merged into master :rofl:. This PR is not about adding a new cop, it's about removing an existing default cop! In my opinion, the easiest transition would be:

* Remove the `Date` recommendation from the cop.
* Disable the cop by default.
* If anybody is interested in enforcing consistent usage of `DateTime` over `Time`, a new style can be proposed for the cop.

That said, I don't have any special interest here. If this is removed, I can add it to my apps as a custom cop! So I'd rather not lose more time discussing this! Whatever @bbatsov decides will be the right call! :smiley:

**Comment by deivid-rodriguez** [comment]
I opened #6199 as an alternative. By the way, we should also remove the rule from the style guide if we are going to remove the cop, no?

**Comment by bbatsov** [comment]
Closing in favour of #6199. Deleting cops creates problems for the end users, so I prefer to disable/deprecate cops instead.

**Pull request closed without merging**
