### PR TITLE
Further cop name standardisation

### PR DESCRIPTION
**Pull request by scottmatthewman**
As discussed in #7077, some further cop renaming to assist with the path to v1.0.

Affected cops in this tranche:

* `Layout/AlignArguments` -> `Layout/ArgumentAlignment`
* `Layout/AlignArray` -> `Layout/ArrayAlignment`
* `Layout/AlignHash` -> `Layout/HashAlignment`
* `Layout/AlignParameters` -> `Layout/ParameterAlignment`
* `Layout/IndentAssignment` -> `Layout/AssingmentIndentation`
* `Layout/IndentFirstArgument` -> `Layout/FirstArgumentIndentation`
* `Layout/IndentFirstArrayElement` -> `Layout/FirstArrayElementIndentation`
* `Layout/IndentFirstHashElement` -> `Layout/FirstHashElementIndentation`
* `Layout/IndentFirstParameter` -> `Layout/FirstParameterIndentation`
* `Layout/IndentHeredoc` -> `Layout/HeredocIndentation`
* `Layout/LeadingBlankLines` -> `Layout/LeadingEmptyLines`
* `Layout/TrailingBlankLines` -> `Layout/TrailingEmptyLines`
* `Lint/DuplicatedKey` -> `Lint/DuplicateHashKey`
* `Lint/HandleExceptions` -> `Lint/SuppressedException`
* `Lint/MultipleCompare` -> `Lint/MultipleComparison`
* `Lint/StringConversionInInterpolation` -> `RedundantStringCoercion`
* `Naming/UncommunicativeBlockParamName` -> `Naming/BlockParameterName`
* `Naming/UncommunicativeMethodParamName` -> `Naming/MethodParameterName`

In addition:

* RuboCop's own use of `disable` directives for `Lint/HandleExceptions` (now `Lint/SuppressedException`) are updated, with older `enable/disable` blocks replaced with end-of-line `disable` statements
* As the list of renamed cops has grown substantially, the lists in `config_obsoletion.rb` and its associated RSpec file have been reordered alphabetically to make future additions and amendments easier.

### CODE REVIEW

**Comment by bbatsov** [comment]
Great work! 🙇 

@rubocop-hq/rubocop-core Any feedback/objections from anyone?

**Comment by bbatsov** [comment]
Just one small thing - probably we should use `VersionChanged` instead of `VersionAdded`. It's still the same cop, just with a different name.

**Comment by bbatsov** [comment]
@scottmatthewman ping :-)

**Comment by scottmatthewman** [comment]
Sorry, have been caught up with work related issues but getting back into this over the weekend!

**Comment by scottmatthewman** [comment]
`VersionAddeds` restored, and rebased to `master`.

**Comment by bbatsov** [comment]
Thanks! 🙇 🎉 🚀

**Pull request merged**
