### PR TITLE
Add new Lint/PreferAllowlistDenylist cop

### PR DESCRIPTION
**Pull request by bjohns2**
# What
Introduce new Cop, `Lint/PreferAllowlistDenylist`, which fails on instances of "whitelist" and "blacklist" in a codebase and suggests using "allowlist" and "denylist" instead.

# Why
"whitelist" and "blacklist" are considered to be harmful language, and many organizations have begun to replace their usage. My organization needed to do the same thing, but found that socialization alone was insufficient to prevent new instances from being introduced. We wrote this cop for our own organization and thought others might find it useful as well. We can open-source our own cop, but would like to leverage the larger community around the official Rubocop repo in order to more quickly accelerate inclusive language in the Ruby community.

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
This topic was discussed a few times in the past (I have to dig up some old conversations) and I strongly feel it's better to have a more generic cop that targets multiple problematic names (via configuration), instead of having a cop for each of them.

**Comment by bjohns2** [comment]
@bbatsov fine by me, but I don't know how to write that. Do you have suggestions for resources explaining how to get started?

**Comment by bbatsov** [comment]
I guess you can check the code of `Naming/MethodParameterName` to see an example of using configuration to provide a forbidden list of names.

**Comment by bbatsov** [comment]
I'm closing this PR due to no recent activity. Feel free to re-open it if you ever come back to it.

**Pull request closed without merging**
