### PR TITLE
Rename IndentArray and IndentHash to IndentFirstArrayElement and IndentFirstHashElement

### PR DESCRIPTION
**Pull request by maxh**
The new names describe more accurately what the cops do and have a naming scheme that matches the one introduced in https://github.com/rubocop-hq/rubocop/pull/6982. With this change, all the `IndentFirst*` cops will appear together in the documentation.

I suggest releasing this in the same version as https://github.com/rubocop-hq/rubocop/pull/6982 and https://github.com/rubocop-hq/rubocop/pull/6981 so that folks only have to go through one set of breaking changes.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
You'll have to rebase to account for your other PRs that were just merged.

**Comment by maxh** [comment]
>You'll have to rebase to account for your other PRs that were just merged.

Done!

**Comment by koic** [comment]
Can you add obsolete messages to `RuboCop::Config::OBSOLETE_COPS`?

Refer #6987.

**Comment by maxh** [comment]
Done! Thanks for pointing that out. https://github.com/rubocop-hq/rubocop/pull/6983/files#diff-769393525d94b12d89d8aeff0df0a5b9R58

**Pull request merged**
