### PR TITLE
Merge duplicate Changes sections in CHANGELOG

### PR DESCRIPTION
**Pull request by rrosenblum**

### CODE REVIEW

**Comment by koic** [comment]
Thanks!

**Comment by rrosenblum** [comment]
Welcome! Thanks for merging it in. Do you know what is going on with some of the builds in Circle?

```
Traceback (most recent call last):
	1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.1/exe/bundle (LoadError)
Exited with code 1
```

**Comment by koic** [comment]
@bquorning is familiar with the build of CircleCI.
https://github.com/rubocop-hq/rubocop/pull/6619#issuecomment-452212866

**Comment by bquorning** [comment]
@rrosenblum Yeah, I need to find some time to fix https://github.com/rubocop-hq/circleci-ruby-snapshot-image/issues/8

**Pull request merged**
