### PR TITLE
Revert "In Rails >= 5, use optional: true, not required: false"

### PR DESCRIPTION
**Pull request by bquorning**
This reverts commit a5105d810f6f107f74a5fe1bf28b805e42e07ff0 (PR #6596) which caused the master build to fail.

/cc @petehamilton, @bbatsov

### CODE REVIEW

**Comment by bquorning** [comment]
Behold the green builds for ruby-head 🎉

**Comment by bquorning** [comment]
Sorry for merging without a review, but I felt that getting a green master branch was pretty important.

**Comment by petehamilton** [comment]
@bquorning no worries - didn't realise my branch was actually failing 🙈. I'll go take a look at that branch now.

**Comment by bquorning** [comment]
Absolutely. I reverted only because your PR was merged by accident and caused the build to fail :-)

**Pull request merged**
