### PR TITLE
Fix a false positive for `Layout/ClosingParenthesisIndentation`

### PR DESCRIPTION
**Pull request by antonzaytsev**
This PR fixes a false negative for `Layout/ClosingParenthesisIndentation` when first argument is multiline.

The following is a reproduction step.
```bash
% rubocop -V
0.59.2 (using Parser 2.5.1.2, running on ruby 2.5.0 x86_64-darwin17)

% cat app/models/users.rb
class User < ApplicationRecord
  def self.complex_find
    where(
      "users.approved_at < ? OR
       users.approved_at IS NULL", 3.days.ago
    )
  end
end

% rubocop app/models/users.rb --only Layout/ClosingParenthesisIndentation -d
or /Users/anton/code/rubocop: configuration from /Users/anton/code/rubocop/.rubocop.yml
configuration from /Users/anton/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-rspec-1.29.1/config/default.yml
configuration from /Users/anton/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-rspec-1.29.1/config/default.yml
Default configuration from /Users/anton/code/rubocop/config/default.yml
Inheriting configuration from /Users/anton/code/rubocop/.rubocop_todo.yml
Inspecting 1 file
Scanning /Users/anton/code/rubocop/users.rb
C

Offenses:

users.rb:6:5: C: Layout/ClosingParenthesisIndentation: Indent ) to column 5 (not 4)
    )
    ^

1 file inspected, 1 offense detected
Finished in 0.5669199999974808 seconds
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by antonzaytsev** [comment]
@rrosenblum good questions actually. Do you have example handy?

**Comment by rrosenblum** [comment]
I don't have a specific example. In general, I tend to think of a false positive as code that generates an offense when it should not. A false negative is when code doesn't produce an offense, but it should.

**Comment by antonzaytsev** [comment]
@rrosenblum you're right, it is a fix for false positive. Thanks!

**Comment by cgriego** [comment]
I've also run into an issue where the following code did not report an offense in 0.55 but does not. I'm not sure if this will fix it, but seems likely?

```ruby
  foo = foo.bar(<<-SQL
    CODE HERE
    SQL
  )
```

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.

**Comment by antonzaytsev** [comment]
@bbatsov rebased, conflict solved.

**Comment by cgriego** [comment]
The conflict was fixed in October but since nothing happened afterward, there’s another conflict.

**Comment by antonzaytsev** [comment]
@cgriego @bbatsov I rebased with latest master and move record in changelog up into master section.

**Comment by Drenmi** [comment]
Thank you, @antonzaytsev! 🙇

**Pull request merged**
