### PR TITLE
[Fix #3727] Add left option to enforced styles for Layout/AlignHash cop

### LINKED ISSUE #3727: Allow Style/AlignHash with key alignment to remove extra spacing before values
When `Style/AlignHash` is configured for key alignment, the space between keys and values is ignored.  Please add the capability to remove extra spacing between keys and values.

## Expected behavior

With this configuration file:
```yaml
Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Style/ExtraSpacing:
  AllowForAlignment: false
```

And this test ruby file:
```ruby
{
  a:  :b,
  c: :d
}
```

I would expect the file to be autocorrected to this:
```ruby
{
  a: :b,
  c: :d
}
```

## Actual behavior

The file is unchanged.

## RuboCop version

```
$ rubocop -V
0.45.0 (using Parser 2.3.1.4, running on ruby 2.3.2 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by albaer**
This PR address #3727.

The `key` option for hash alignment enforces that the keys are left-aligned, but does not look at the placement of hash rockets or values. So all of these are accepted:
```ruby
h1 = { a: 1,
       bbb: 2 }
h2 = { a:     1,
       bbb: 2 }
h3 = { a      =>1,
       b =>    2 }
```
It would be nice have a more strict option, especially so that autocorrect is able to clean up spacing issues in hashes. Since `key` is the default option and there are [explicit tests checking that it doesn't check separator or value placement](https://github.com/albaer/rubocop/blob/hash_align_left/spec/rubocop/cop/layout/align_hash_spec.rb#L220), I added a `left` option instead of modifying `key`. It enforces everything that `key` does, but also checks (and corrects) whitespace issues. It expects keys to be left-aligned and single spaces before hash rockets and the values. So the example above would be corrected to:
```ruby
h1 = { a: 1,
       bbb: 2 }
h2 = { a: 1,
       bbb: 2 }
h3 = { a => 1,
       b => 2 }
```
-----------------

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

### CODE REVIEW

**Comment by rrosenblum** [comment]
I like the fix. It was a safe idea to create a new configuration given that we have explicit tests. However I'm not sure it is worth creating a new configuration, and I would like to call those tests into question.

As you said
> The `key` option for hash alignment enforces that the keys are left-aligned, but does not look at the placement of hash rockets or values

From the documentation for `AlignHash`
> Check that the keys, separators, and values of a multi-line hash literal are aligned according to configuration. The configuration options are:
> * key (left align keys)
> * separator (align hash rockets and colons, right align keys)
> * table (left align keys, hash rockets, and values)

To me, it feels like the current configurations don't obey the intention of the cop. All of the configurations should be checking for alignment of keys, separators, and values.

I'm not sure if anyone would be upset or not if `key` were updated to work like `left`. If there is value in maintaining `key` and `left` separately, maybe `left` should become the new default.

Anyone else have thoughts on this?

**Comment by albaer** [comment]
Great! I expected `key` to enforce separator and value placement when I ran the cop, but I didn't want to assume that everyone wanted potentially build-breaking changes to the default configurations without a little more discussion. I'm happy to update the PR to make `key` behave like `left` or to make `left` the default if that's what ends up making the most sense.

**Comment by rrosenblum** [comment]
I would hold off on making any changes until others have reviewed the code and weighed in with their opinions.

**Comment by bbatsov** [comment]
@rubocop-hq/rubocop-core Any thoughts on the proposed change?

**Comment by bbatsov** [comment]
For the protocol - I think that we should change the behaviour of `key`, as suggested by @rrosenblum.

**Comment by bbatsov** [comment]
@albaer ping :-)

**Comment by albaer** [comment]
Thanks for the nudge! I adjusted this PR to enforce single spaces in the `key` option, and it had the (somewhat ironic) side effect of making all the the rubocop tasks fail (e.g. [this one](https://circleci.com/gh/rubocop-hq/rubocop/11730?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). It turned out to be a good chance to see the autocorrect in action, and revealed a bug when the key and value are on different lines.

I'll sort that bug out next week, but since this is the default configuration, I'm wondering if this might be a problem for other people whose builds will break when they upgrade rubocop. Are you still good with me changing the key option without giving people the ability to go back to the softer configuration?

**Comment by albaer** [comment]
Okay, I fixed the bug with values that start on a new line and ran autocorrect on the entire project in a separate commit. This PR is rebased, passing all checks, and ready for additional review or discussion.

**Comment by bbatsov** [comment]
I'm fine with the change, although I have to admit I was starting to warm up to aligned hash literals. But I guess the people who like them can simply switch to `table`, as they were supposed to.

**Comment by bbatsov** [comment]
@albaer I see now objections. Please, rebase on top of the current `master` and I'll merge this.

**Comment by albaer** [comment]
@bbatsov This is rebased and up to date. Just let me know if there's anything else I can do.

**Comment by bbatsov** [comment]
I think it took us a while, but we're ready to go. Sorry for the slow turnaround!

Looking forward more contributions from you down the road!

**Comment by albaer** [comment]
🎉 I'm happy to be able to contribute to a tool I use so often. Thanks for all your work on rubocop!

**Pull request merged**
