### PR TITLE
[Fix #5465] Fix Layout/ClassStructure to allow grouping macros by their visibility.

### LINKED ISSUE #5465: Layout/ClassStructure cop should allow grouping macros by their visibility
## Expected behavior

There should be a way to configure different visibility levels for macros to avoid false positives with the ordering of protected/private macros.

## Actual behavior

Currently, there is no way to make such configuration.

## Steps to reproduce the problem

Given the following configuration:

```yaml
Layout/ClassStructure:
  Categories:
    - attribute:
      - attr_accessor
      - attr_writer
      - attr_reader
  ExpectedOrder:
    - attribute
    - initializer
```
And the following class definition:

```ruby
class Person
  attr_accessor :name

  def initialize(name)
    @name = name
  end

  private

  attr_accessor :age
end
```

Rubocop gives the following output:

```
person.rb:10:3: C: Layout/ClassStructure: attribute is supposed to appear before initializer.
  attr_accessor :age
  ^^^^^^^^^^^^^^^^^^
```

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.3.0 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by gPrado**
Fix #5465 by allowing the configuration of macros prefixed by their visibility levels.

Given the following example class:

```ruby
class Person
  attr_accessor :name

  def initialize(name)
    @name = name
  end

  private

  attr_accessor :age
end
```

It is possible to use the following configuration to avoid issues with `private attr_accessor`:

```yaml
Layout/ClassStructure:
  Categories:
    - attribute:
      - attr_accessor
      - attr_writer
      - attr_reader
    - private_attribute:
      - private_attr_accessor
      - private_attr_writer
      - private_attr_reader
  ExpectedOrder:
    - attribute
    - initializer
    - private_attribute
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Is this style common? I've never seen it in my personal programming practice. I get the general idea, but I'm always wary of making a cop more complex to accommodate for some pretty peculiar style of programming.

**Comment by gPrado** [comment]
A simple search for Ruby use of private `attr_accessor`'s led to some results, e.g.:
- https://github.com/bbatsov/ruby-style-guide/issues/538
- https://github.com/bbatsov/ruby-style-guide/issues/73
- https://forum.upcase.com/t/using-instance-variables-vs-attribute-accessors/1788/6

So, I think there are some people that use this kind of style (I/my company use it too!). Furthermore, I think the complexity added to cop is very small, since the visibility check is already used for other purposes.
However, I'd like to have some feedback on the PR, maybe it'd better to use another separator (instead of the underscore sign), to make it more clear that `private`/`public` are modifiers and not part of the method's name? E.g.:
```yaml
Layout/ClassStructure:
  Categories:
    - attribute:
      - attr_accessor
      - attr_writer
      - attr_reader
    - private_attribute:
      - private-attr_accessor
      - private-attr_writer
      - private-attr_reader
  ExpectedOrder:
    - attribute
    - initializer
    - private_attribute
```

**Comment by skatkov** [comment]
Pretty common in my case. Use this style a lot myself and seen other developers that use it too.

**Comment by bbatsov** [comment]
@koic @pocke @jonas054 @garettarrowood @rrosenblum @Drenmi Any thoughts on this?

**Comment by garettarrowood** [comment]
This is a coding style we use at my work. Mostly with `attr_reader`s specified below stand alone `private` access modifiers.

**Comment by koic** [comment]
In my opinion, I don't personal programming with private (or protected) `attr_*`, so there is no strong will to this change.
However, by investigating using pattern matching by `ag "private\n+\s*attr"`, I could look the use cases in this rubocop repository, rails repository, etc.
I'd like to ask other developer's opinions :-)

**Comment by koic** [comment]
And I was concerned about whether it is necessary to change the settings of `attr_accessor`, `attr_writer`, and `attr_reader` depending on access modifiers. I don't think the order will change according to access modifiers.

In other words, I thought that it would be simpler if it could be set in one place overall rather than letting `attr_accessor`, `attr_writer`, and `attr_reader` be set for each access modifiers.

**Comment by rrosenblum** [comment]
> In other words, I thought that it would be simpler if it could be set in one place overall rather than letting `attr_accessor`, `attr_writer`, and `attr_reader` be set for each access modifiers.

I agree, it seems weird that someone would want to set a different order for these based on if they are `public`, `protected`, or `private`.

**Comment by bbatsov** [comment]
So, what are we doing here in the end? Are we just closing this for lack of recent activity or someone wants to work further on it?

**Comment by gPrado** [comment]
I could still work on this, do you think @koic and @rrosenblum suggestions are enough?

**Comment by bbatsov** [comment]
Yeah, I think they are.

**Comment by Drenmi** [comment]
@gPrado Are you still intending to finish this PR? I'm okay with leaving it open for a few days if so, but if not I'll close it for now to clear up the PR queue a bit. 🙂

**Comment by gPrado** [comment]
@Drenmi actually I had it done already, but forgot to ping you here. I've just rebased, please review/merge it.

**Pull request merged**
