### PR TITLE
[Fix #8683] Make naming cops work with non-ascii characters

### LINKED ISSUE #8683: Naming/MethodName false positive
Detects mothod names with non ascii characters. crear_línea_última_vista is in snake_case
```
módulos/última_vez.rb:120:9: C: Naming/MethodName: Use snake_case for method names.
    def crear_línea_última_vista(msj)
        ^^^^^^^^^^^^^^^^^^^^^^^^
```

Also happens with Naming/FileName and Naming/VariableName

--------

## Expected behavior

Any detection

## Actual behavior

Detected in non snake_case style

## Steps to reproduce the problem

Create a method named 'crear_línea_última_vista'

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.6.6 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes https://github.com/rubocop-hq/rubocop/issues/8683

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by marcandre** [comment]
Good work, thanks!

**Comment by bbatsov** [comment]
I was going to say that I'd have this be configurable, as I don't want non-ascii characters in any names for various reasons. I guess you could have that the behaviour you changed was a feature, not a bug. :) Anyways, we can always adjust this later.

**Comment by marcandre** [comment]
Sure, or there could be a cop for that...
This PR changed the definition of what is camel case vs snake case though, which is a concept that is valid for non-ascii characters.
I doubt there are much cases of unwanted non-ascii characters in codebases though.

**Comment by bbatsov** [comment]
Well, I've worked on codebases where we had international teams and some people would name stuff in their language (e.g. German or French) instead of English and this caused some confusion and frustration. I can imagine some valid use-cases for non-ascii characters, but not that many of them. :-)

**Pull request merged**
