### PR TITLE
Change organization URL to rubocop-hq

### PR DESCRIPTION
**Pull request by koic**
Change organization URL from https://github.com/bbatsov to https://github.com/rubocop-hq/rubocop.

I heard that this is one of the milestone activities for RuboCop 1.0.0 at RubyKaigi 2018.
http://rubykaigi.org/2018/presentations/bbatsov.html#may31

In this PR, change CHANGELOG.md, relnotes, and service URLs (such as Travis CI, etc) are kept intact.

For each reason.

- Old URLs in CHANGELOG.md and relnotes are redirected, so this PR leaves it.
- Service URLs aren't ready for the new rubocop-hq organization, so this PR leaves it.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
That was fast! Thanks!

**Comment by koic** [comment]
It was nice to see your presentation. Thank you!

**Comment by koic** [comment]
@bbatsov Repository URL has changed, so perhaps Travis CI (and Appveyor?) is not working. Would you please check the CI setting?

**Comment by Drenmi** [comment]
Is the presentation online yet? I'm not at Kaigi this year. 🙂

**Comment by bbatsov** [comment]
> @bbatsov Repository URL has changed, so perhaps Travis CI (and Appveyor?) is not working. Would you please check the CI setting?

Unfortunately Travis CI still doesn't show the new org, even though I synced my profile a couple of times already. That's why I can't enable the build for the "new" repo.

**Comment by bbatsov** [comment]
@Drenmi It's here https://speakerdeck.com/bbatsov/all-about-rubocop-rubykaigi-2018

Btw, for AppSurveyor I can't even find how to force a resync of my GitHub orgs. Maybe this needs some time?

**Comment by bbatsov** [comment]
OK, I've sorted out Travis CI and AppSurveyor. I should stop doing things when I'm too sleepy. 😆

**Comment by koic** [comment]
@Drenmi FYI, @bbatsov's presentation video at RubyKaigi 2018 was published 🎤 
https://www.youtube.com/watch?v=nrHjVCuVsGA

**Pull request merged**
