### PR TITLE
Windows - add Actions CI, remove AppVeyor, two minor spec fixes

### PR DESCRIPTION
**Pull request by MSP-Greg**
Three commits:

1. 'specs - Allow lower case drive letter on Windows' - two spec files - drives can be upper or lower case.  Fixes regex's to allow that.

2. 'add GitHub Actions CI' - Windows, Ruby 2.4 thru head/master.  Ubuntu & macOS also pass.

3. 'Delete appveyor.yml'

Notes:

* No CodeClimate
* Failure in any test 'suite' causes job to stop
* If Actions is not currently used, PR's will not run.  See https://github.com/MSP-Greg/rubocop/actions/runs/82475987

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by MSP-Greg** [comment]
> difference in speed with other CIs

I've kept track of Windows CI, and AppVeyor normally runs one job, so all jobs are serial.  Actions will run 20 Ubuntu/Windows jobs and 5 macOS at once.

As to speed, Actions Windows is about 10 to 15% slower than AppVeyor at it's fastest, but AppVeyor's speed varies a **great** deal, depending on the time of day and day of week...

**Comment by bbatsov** [comment]
So, what are we aiming for here? Replacing both AppVeyor and CircleCI? In general I've been happy with CircleCI, so I'm curious to hear what are the advantages of GitHub actions over it.

**Comment by MSP-Greg** [comment]
> So, what are we aiming for here?

World domination.

Sorry.  Anyway, I noticed that the AppVeyor CI was a bit light, and wasn't sure if that was due to the serial job issue.  I wrote the yaml for Actions, got it passing, and then thought I might as well check Ubuntu & macOS.  I did not add (or try) JRuby or TruffleRuby.

There are three test 'types', CircleCI is set up to run all three independently.  As written, Actions is not, it will stop a job on the first failure, and CodeClimate and the 'doc' CI aren't included in Actions.

I think there are solutions to all of the above issues.  Note that Actions can use multiple yml files, and each file can have multiple job definitions.

> Replacing both AppVeyor and CircleCI?

This might have been better as an issue or a draft PR.  For now, increasing the Windows CI might be a good idea?  IOW, remove the Ubuntu & macOS from Actions.

**Off topic**

Actions is new, but most of the services it's competing with are reasonably mature.  Things were somewhat static during it's public beta, and many changes are still being made.  At present, it does not have efficient implementations/solutions for every feature in the other services.

The main reasons I think Actions may work well:

1. The web UI works well and is well integrated with GH.
2. Cross-platform use is reasonably easy, and the scripts are short.
3. Compared to Travis & AppVeyor, the increased parallel job limits shorten CI time.

**Comment by bbatsov** [comment]
> This might have been better as an issue or a draft PR. For now, increasing the Windows CI might be a good idea? IOW, remove the Ubuntu & macOS from Actions.

Sounds like a plan to me!

**Comment by MSP-Greg** [comment]
Done.  Removed appveyor.yml with an additional commit.

JFYI, this all started when I added rubocop master docs to [MSP-Greg.github.io](https://msp-greg.github.io/rubocop/), also added `rubocop-performance`.  Manual files are contained in the 'Docs' lists.  YARD based, using commonmarker for the md.

**Comment by bbatsov** [comment]
You'll also have to update the status icon in the README.

**Comment by MSP-Greg** [comment]
> You'll also have to update the status icon in the README.

Sorry.  Fixed.

**Pull request merged**
