### PR TITLE
[Fix #8993] Allow `ExcludedMethods` config of `Metrics/MethodLength` cop to contain regex

### LINKED ISSUE #8993: Metrics/MethodLength ExcludedMethods Regex
## Is your feature request related to a problem? Please describe.

Maybe this one is actually working, but I couldn't do it. It would be nice if you could add a regular expression to the ExludedMethods array.

## Describe the solution you'd like
I would love to add Regex to ExludedMethods, or to know how if it's already possible.

Something like this:
`ExcludedMethods: [!ruby/regexp \b\w*params\w*\b\$/, 'create', 'update', 'new', 'edit']`
meaning all methods which have **params** string in it would be ignored, trying to archive that my controllers and their's permitted params are always skipped when MethodLenght check is being controlled.

## Describe alternatives you've considered
Ofc I could skip this check for whole controllers folder, but I want it to be as much precise as possible.

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #8993

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm wondering if this should be mentioned in the docs, as I have a feeling we're not consistent with this behavior across cops. Probably somewhere it's a string match and somewhere a regexp match.

**Comment by marcandre** [comment]
> Probably somewhere it's a string match and somewhere a regexp match.

Ideally it should be general (string or regexp) everywhere though, no?

**Comment by tejasbubane** [comment]
> Ideally it should be general (string or regexp) everywhere though, no?

I think we have some inconsistency with the configuration naming. `ExcludedMethods` is used only by two cops: `Metrics/BlockLength` and `Metrics/MethodLength`. Rest use `IgnoredMethods`.

**Comment by bbatsov** [comment]
Yep, I was going to mention this as well, but it slipped my mind. I think we should unify this and just add two possible names for the problematic cops, so that we don't break backwards compatibility. 

> Ideally it should be general (string or regexp) everywhere though, no?

Yep. I guess we should go for regex everywhere, as it's more flexible.

**Comment by bbatsov** [comment]
@dvandersluis I see you liked the suggestion I made, so I'm wondering if you'd be willing to implement this. 😄

**Comment by dvandersluis** [comment]
@bbatsov definitely! I will take a look in the next couple days.

**Pull request merged**
