### PR TITLE
Add new `Layout/AutocorrectableLineLength` cop

### PR DESCRIPTION
**Pull request by maxh**
Similar to https://github.com/rubocop-hq/rubocop/pull/6824 and https://github.com/rubocop-hq/rubocop/pull/6826, this is a cop that we developed internally so that we could achieve more opinionated Ruby formatting using Rubocop.

It programmatically shortens certain lines by conservatively inserting line breaks into long method calls, hashes, and arrays. It's a bit complex, but I think the code comments and documentation do a reasonable job explaining both the implementation and intended usage.

I'm open to suggestions as how best to upstream this. I'm not sure, for example, if I should try to integrate it into `Metrics/LineLength`, or vice versa.

Open sourced from a Flexport-internal Ruby formatting project.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
That's a really cool cop overall! 

> I'm open to suggestions as how best to upstream this. I'm not sure, for example, if I should try to integrate it into Metrics/LineLength, or vice versa.

I'll have to think about this. I'd also be curious to hear what the rest of @rubocop-hq/rubocop-core think on the subject of having a separate cop or merging this in the existing one.

**Comment by jonas054** [comment]
It's an awesome new feature, @maxh!

I'm leaning towards incorporation into the existing `Layout/LineLength` cop as the best alternative. We'd get rid of double reporting of the same offense, and also of the trouble with two `Max` parameters or a shared `Max` parameter (both have their drawbacks). Do you think it's doable?

**Comment by jonas054** [comment]
> This new logic cannot autocorrect all instances of Layout/LineLength -- only certain long lines that have breakable hashs, method calls, arrays, etc. Is it ok to have the LineLength cop be partially but not completely auto-correctable?

Yes, that's no problem. There are already several cops that autocorrect only some (or perhaps most) of the offenses they report.

> LineLength is in the namespace Metrics. The other cops in that namespace don't support autocorrect and tend to be computed summary stats of code. It might seem more natural to me for this cop to live in Layout or Style.

No matter where you put it, the `LineLength` cop will be a bit different from its department colleagues. It would fit better in `Layout` than in `Style` since it only makes whitespace changes, but it has a `Max` parameter that can be set by `--auto-gen-config` and that's why it's been put in the `Metrics` department. It's better to let it stay there IMO.

So, green light from me at least, to go ahead with the merger. I hope @bbatsov agrees.

**Comment by maxh** [comment]
Please take a look at the new PR "Add initial autocorrection support to LineLength cop" https://github.com/rubocop-hq/rubocop/pull/6927. Thanks!

**Pull request closed without merging**
