### PR TITLE
[Fix #6266] Run HasManyOrHasOneDependent only for ActiveRecord class

### LINKED ISSUE #6266: Rails/HasManyOrHasOneDependent Cop & ActiveResource relations
Rails/HasManyOrHasOneDependent Cop wants me to define a :dependent option for a has_many relation for a class that extends from a ActiveResource model. Though, for a ActiveResource relation :dependent is not a valid option.

--------

## Expected behavior

The Rails/HasManyOrHasOneDependent error should not be triggered for ActiveResource models.

## Actual behavior

Rails/HasManyOrHasOneDependent is detected 

## Steps to reproduce the problem
Include ActiveResource in your project:
```
gem 'activeresource', require: 'active_resource'
```

Create a ActiveResource class for talking to a REST API:
```
module API
  class User < ActiveResource::Base
    has_many :projects, class_name: 'API::Project'
  end
end
```

Running Rubocop gives the following:

```
app/models/api/user.rb:4:5: C: Rails/HasManyOrHasOneDependent: Specify a :dependent option.
    has_many :projects, class_name: 'API::Project'
    ^^^^^^^^
```

but If you add the :dependent option, ActiveResource will throw an exception on runtime:
```
Failure/Error: has_many :projects, class_name: 'API::Project', dependent: :destroy

ArgumentError:
  Unknown key: :dependent. Valid keys are: :class_name
```

## RuboCop version

0.59.0 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes: https://github.com/rubocop-hq/rubocop/issues/6266

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.

**Comment by tejasbubane** [comment]
@bbatsov Done.

**Comment by bbatsov** [comment]
@tejasbubane Btw, other ActiveRecord specific cops should probably behave similarly.

**Comment by koic** [comment]
PR #6315 fixes a regression of this change.

Apart from that, we need to consider false negative when using mix-in.
https://github.com/rubocop-hq/rubocop/issues/6266#issuecomment-422651337

I have not ideas yet, but this approach to directly check superclass will have false negative problem.

**Comment by koic** [comment]
This is one idea. It seems better to check whether it is `ActiveResource::Base` instead of `ActiveRecord::Base` or `ApplicationRecord`. It does not check if the superclass is `ActiveResource::Base`.

**Pull request merged**
