### PR TITLE
Add new `Style/DocumentDynamicEvalDefinition` cop

### PR DESCRIPTION
**Pull request by fatkodima**
This is an implementation of https://rubystyle.guide/#eval-comment-docs

### CODE REVIEW

**Comment by bbatsov** [comment]
Cool idea, but we definitely need a better name for this cop. The achor in the style guide is horrible and I guess you derived the cop name from it. :-) I'm wondering about something like "DocumentDynamicEvalDefinition" or something along those lines. As usual, @rubocop-hq/rubocop-core, your ideas are most welcome! :-)

**Review by marcandre — APPROVED** [review]

**Comment by bbatsov** [comment]
Another potential name "DynamicMethodDefinitionDocumentation".

**Comment by fatkodima** [comment]
Changed the name to `DocumentDynamicEvalDefinition`. This variant looks nicer, imo.

**Comment by bbatsov** [comment]
Fine by me! Thanks!

**Pull request merged**
