### PR TITLE
Introduce Pacman style formatter

### PR DESCRIPTION
**Pull request by crojasaragonez**
**Introduce Pacman style formatter.**

* This is inspired by the Pacman formatter for RSpec [rspec_pacman_formatter](https://github.com/go-labs/rspec_pacman_formatter)
-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
This is a fun feature. However, it looks to me that it is not a feature maintained by RuboCop core.
I think it should be created as a custom formatter extension gem like rspec_pacman_formatter.
https://github.com/rubocop-hq/rubocop/blob/v0.74.0/manual/extensions.md

**Comment by bbatsov** [comment]
Let me think about this. The code seems simple enough and introduces no extra deps, so we might actually have this in RuboCop itself.

**Comment by bbatsov** [comment]
Let's get the tests passing first. 😉

**Comment by crojasaragonez** [comment]
> Let's get the tests passing first. wink

Tests are passing now

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
