### PR TITLE
[Fix #5977] Remove Performance cops

### LINKED ISSUE #5977: Extract Performance Cops into a separate gem
Performance cops have to extracted into a standalone gem (named something like rubocop-performance or whatever).

The reason for this decision is simple. I want RuboCop to be focused just on Ruby and have no framework/library/runtime dependant pieces for the sake of being easier to focus on evolving it. Creating more extensions should also help us come up with a good official API for them. Performance cops are all MRI focused and are highly dependent of the version of MRI you're using, so they don't belong in the core RuboCop. 

Any volunteers to do this? I was always ambivalent towards the performance checks (as they often come at the expense of readability), so I'm not particularly interested in working on this.

### PR DESCRIPTION
**Pull request by koic**
Fixes #5977.

This PR removes Performance cops from RuboCop core.

These cops were transferred to rubocop-hq/rubocop-performance repository.
https://github.com/rubocop-hq/rubocop-performance

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
It may be better to merge this PR when we decide the next release version is RuboCop 0.58.

**Comment by bbatsov** [comment]
I agree. I'll wait for a couple of days to see if we'll need another bugfix release for 0.67 and aim to merge this on Monday.

**Comment by bbatsov** [comment]
There are a few small problems with `RescuedExceptionsVariableName` that would probably warrant a bug-fix release, but they can also go to 0.68.0, as they aren't anything urgent.

**Comment by bbatsov** [comment]
P.S. Once again - fantastic work, @koic!

**Comment by koic** [comment]
I get it! Thanks too, @bbatsov!
And I will release RuboCop Performance 1.1.0.
https://github.com/rubocop-hq/rubocop-performance/pull/41

**Pull request merged**
