### PR TITLE
Handle array spread for `change_column_default` in `Rails/ReversibleMigration`

### LINKED ISSUE #6729: "Rails/ReversibleMigration incorrect flags reversible usage of change_column_default(without :from and :to)
## Expected behavior

Should ignore reversible usage of `change_column_default` in the following migration:

```rb
require_relative '../helpers/reversible_helpers'

class AddIsRedirectEnabledFlagToSets < ActiveRecord::Migration[5.1]
  include ReversibleHelpers

  def change
    column = [:test_sets, :is_redirect_enabled]
    add_column(*column, :boolean)
    up_only do
      execute <<~SQL
        update #{column[0]}
        set #{column[1]} = not (
          redirect_link is null
          or trim(redirect_link) = ''
        )
      SQL
    end
    change_column_null(*column, false)
    change_column_default(*column, from: nil, to: false)
  end
end
```

## Actual behavior

```
db/migrate/20190129042815_add_is_redirect_enabled_flag_to_sets.rb:19:5: C: Rails/ReversibleMigration: change_column_default(without :from and :to) is not reversible.
    change_column_default(*column, from: nil, to: false)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

Check the above migration. You can remove the `require_relative` and `up_only` statements.

## RuboCop version

```
-> bundle exec rubocop -V
0.62.0 (using Parser 2.5.3.0, running on ruby 2.4.5 x86_64-darwin17)
```

Not latest, sorry. I couldn't find any recent related issues or PRs so I assume it's not fixed. I'm not in a position to upgrade just now because it takes a long time to deal with all the rule changes.

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #6729 

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

### CODE REVIEW

**Comment by rhys-vdw** [comment]
You have a bot that closes MRs that are waiting to be merged when no human has yet to review them?

**Comment by bbatsov** [comment]
So it would seem. :-) On the bright side - the bot reminds to review forgotten PRs.

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.

**Comment by tejasbubane** [comment]
@bbatsov Rebased on master and conflicts resolved.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
