### PR TITLE
Relax regexp_parser requirement.

### PR DESCRIPTION
**Pull request by marcandre**
See https://github.com/rubocop-hq/rubocop/pull/9102#issuecomment-737487246

### CODE REVIEW

**Comment by marcandre** [comment]
Should we issue a warning if the loaded version is < 2?

**Comment by bbatsov** [comment]
Probably not. Users tend to complain about those. :-)

**Comment by tas50** [comment]
Thanks @marcandre. This unblocks me in a major way.

**Comment by marcandre** [comment]
Cool, thanks. Merged.

**Pull request merged**
