### PR TITLE
[Fix #6142] Ignore keyword arguments in `Rails/Delegate`

### LINKED ISSUE #6142: Rubocop recognises keyword argument.
## Expected behavior

The keyword argument is different from the argument and must be handled separately.

## Actual behavior

RuboCop does not seem to be able to distinguish between these two.

## Steps to reproduce the problem

```ruby
   # Rails/Delegate
   it 'ignores trivial delegate with mismatched keyword arguments' do
     expect_no_offenses(<<-RUBY.strip_indent)
       def fox(foo:)
         bar.fox(foo)
       end
     RUBY
   end
```

## RuboCop version

```
$ rubocop -V
0.58.1 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by sunny**
Closes #6142 

-----------------

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
Thanks for opening a pull request. Would you please rebase from the current master branch?

**Comment by sunny** [comment]
@koic Sure thing! Here it is.

**Comment by koic** [comment]
@sunny Thanks!

**Comment by sunny** [comment]
No, thank YOU! :)

**Pull request merged**
