### PR TITLE
Add option to filter files passed via STDIN

### PR DESCRIPTION
**Pull request by goddamnhippie**
This PR add the `--strict-stdin` CLI option to filter files passed via STDIN and discard files detected as non-ruby.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
What's the reasoning for this change? Usually when you pipe something to stdin you don't care about extensions.

**Comment by goddamnhippie** [comment]
I have a pre-commit git hook that lints files and it's erroring on `Gemfile.lock` and YAML files:

```bash
#!/usr/bin/env bash

set -Eeuo pipefail

git diff --cached --name-only --diff-filter=ACM | while read -r file; do
  bundle exec rubocop -RP -c config/rubocop.yml --force-exclusion --strict-stdin --stdin "$file" < <(git show :"$file")
done
```

So I thought I could take advantage of the filters already on rubocop instead of doing the filtering with the script.

**Comment by goddamnhippie** [comment]
@bbatsov is that not the right approach?

**Comment by bbatsov** [comment]
I'm not convinced it's RuboCop's responsibility to be doing such filtering. I understand your reasoning, but I'm always wary of adding functionality that probably would in the end be used only by the person who submitted it. 

I'll leave this PR open for now to see if someone else would be interested in this extra flag, but generally I'm leaning towards not accepting it.

**Comment by goddamnhippie** [comment]
Ok, thanks for replying, I'll filter in the script.

**Pull request closed without merging**
