### PR TITLE
Change indent rule for `Layout/ClosingHeredocIndentation` cop

### PR DESCRIPTION
**Pull request by koic**
## Summary

Follow up of #5557 (comment).

In the current RuboCop codes, it seems that there are many cases that are aligned at beggining of method definition, not an argument.

This PR will change to accept both the following case.

```ruby
# good
foo arg,
    <<~EOS
  Hi
EOS

# good
foo arg,
    <<~EOS
      Hi
    EOS
```

On other hand, this PR will change to deny the following case.

```ruby
# bad

# heredoc contents is before closing heredoc.
foo arg,
    <<~EOS
  Hi
    EOS
```

And this PR applies a new indentation rule, so it reverts the (auto)corrected codes in #5557.
(https://github.com/rubocop-hq/rubocop/commit/fa5f1dff4531c71648c9d96061709099770d081b)

## Other Information

Autocorrect has not been implemented yet for the case where heredoc contents are before heredoc closing.

```diff
     it 'registers an offense for camel case local variables marked as unused' do
       expect_offense(<<-RUBY.strip_indent)
-    _myLocal = 1
-    ^^^^^^^^ Use snake_case for variable names.
-    RUBY
+        _myLocal = 1
+        ^^^^^^^^ Use snake_case for variable names.
+      RUBY
     end
```

In this commit, heredoc contents are indented by hand craft.

Cc @bbatsov @Drenmi @siegfault 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Good call, @koic! I guess I didn't think enough about this. I wonder, however, if those shouldn't be two enforced styles, as it seems to me that most people would like chose just one of them for their codebases.

**Comment by bbatsov** [comment]
Anyways, I'll merge your PR in its current form as it's clearly an improvement over what we have right now and we can decide how to further improve this later.

**Comment by koic** [comment]
@bbatsov Thank you for review!
I also thought about enforced styles. The following two styles are conceivable.

```ruby
#
# @example EnforcedStyle: method
#   # good
#   foo arg,
#       <<~EOS
#     Hi
#   EOS
#
# @example EnforcedStyle: argument
#   # good
#   foo arg,
#       <<~EOS
#         Hi
#       EOS
#
```

Currently I think that it corresponds to the third style, `EnforcedStyle: both`.

I also think that we can continue to improve this cop rule yet.
For example, we can decide name of enforced styles and default style later :-)

**Comment by koic** [comment]
And when writing a method call in one line, I think that the following style is always accepted.

```ruby
#  # good
#  foo arg, <<~EOS
#    Hi
#  EOS
```

**Comment by siegfault** [comment]
@koic thanks for following up with this change! I definitely wasn't sure how best to handle that open question. I know it's already merged, but this looks good to me!

**Pull request merged**
