### PR TITLE
Remove ascii spec duplication

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This is a follow up to https://github.com/rubocop-hq/rubocop/pull/6220#issuecomment-416057213. With these changes, the `ascii_spec` task goes down from ~50 seconds to ~2 seconds.

I intentionally added https://github.com/rubocop-hq/rubocop/commit/0451970f16c40825acf5a95c83f52c6edfb2c2ab temporarily to prove that these specs are actually preventing regressions, so are worth keeping.
 
-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Well, I'm now doing several more tests, and there's quite a few places in the code where regressions can happen unless we run the specs against non-utf8 external encodings. Basically, everytime we read from a file, it's safest to explicitly pass the encoding in order to support these cases. And this can only be catched by running specs against non-utf8 external encodings. This is also a very realistic use case since base docker images usually don't set their default OS encoding to UTF-8.

So, in my opinion it's safest to keep things as they are. Each CI matrix entry, thanks to rspec-queue, takes currently around 50 seconds to run. That's pretty good IMO.

**Comment by bquorning** [comment]
Could we get away with running just 1 ascii test, e.g. using the latest MRI version, or do we need one ascii run per supported Ruby?

**Comment by bbatsov** [comment]
Yeah, I was thinking this could be limited just to one build. Btw, what's stopping us for just using a different external encoding in the tests by default?

**Comment by deivid-rodriguez** [comment]
> Could we get away with running just 1 ascii test, e.g. using the latest MRI version, or do we need one ascii run per supported Ruby?

I figure we could do that, but encoding has been one of the areas most subject to change across ruby versions. So, I'm not sure.

> Yeah, I was thinking this could be limited just to one build. Btw, what's stopping us for just using a different external encoding in the tests by default?

That's a good point. Not sure I feel confortable about all of our specs launching ruby in a non-standard way, and with a non-standard encoding, but I don't have a specific issue in mind... :man_shrugging: 

One thing I thought we could do to optimize CircleCI usage is having two stages. One that runs the most recent version, and only if that stage passes, the rest of the jobs are run. The rationale is that in 99% of the cases, if a PR has one failure, that failure happens consistently accross all versions. So in the case of failed PRs, we would save a few useless jobs from being run. Not sure how much difference it would make though, since rubocop contributions are tipically pretty neat and many times are green on the first push...

**Comment by bbatsov** [comment]
Yep, I remember pretty much no failures of these builds that's why I started to question their value a while ago. 

> I figure we could do that, but encoding has been one of the areas most subject to change across ruby versions. So, I'm not sure.

I thought that after 1.9 and 2.0 there were no encoding changes. Unless I'm missing something. 

I also wonder if we can just warn users who are not using utf-8 as their external encoding. Is there any reason to do this in 2018?

**Comment by deivid-rodriguez** [comment]
> If we run all our tests with ASCII encoding, don’t we risk introducing a change that doesn’t work for UTF8 encoding?

That's my guess, but I don't have anything in mind to prove (that'd be introducing a change in lib that fails the regular spec, but passes the ascii spec).

> Across all the Ruby versions running the specs in this PR, I only see one failing spec example: “RuboCop::Cop::Style::StringLiterals configured with single quotes preferred autocorrects words with non-ascii chars”. So I still stand by my suggestion to run the entire spec suite with ASCII, but only on Ruby 2.5 (and definitely not on JRuby).

The thing is, I made several experiments and there's many changes that can be introduced that keep the regular test suite green, and only introduce failures in ascii specs. You want me to push those changes too so we can see the examples?

> I thought that after 1.9 and 2.0 there were no encoding changes. Unless I'm missing something.

I meant traditionally, but yeah, things have been more stable in this regard for a while now.

> I also wonder if we can just warn users who are not using utf-8 as their external encoding.

I don't think it is rubocop's job to warn users about how they configure their environment. I think it'd be great to push for a change in base docker images, but in any case, if rubocop can work under any encoding, why shouldn't it? This slows down CI a bit, but since I fixed all those encoding issues a while ago, I haven't seen any more problems reported, so that's good for rubocop's maintainance.

**Comment by bbatsov** [comment]
> The thing is, I made several experiments and there's many changes that can be introduced that keep the regular test suite green, and only introduce failures in ascii specs. You want me to push those changes too so we can see the examples?

At the very least we should document better the need for this. 

Let's just leave the ascii run for the latest supported Ruby version. After this long discussion this seems like the most reasonable approach.

**Comment by deivid-rodriguez** [comment]
I'm going to close this since I'm not convinced about it, so I'd rather leave this task for someone else :)

**Pull request closed without merging**
