### PR TITLE
[Fix #6637] Promoted Performance/LstripRstrip to Style/LstripRstrip

### LINKED ISSUE #6637: promote Performance/LstripRstrip to Style/LstripRstrip
Unlike many other Performance cops `Performance/LstripRstrip` is not making code less readable and is a good idea independent from performance improvements.

As  #5977 will cause performance cops to be disabled by default I suggest to rescue this one as it is useful to avoid `lstrip.rstrip` where `strip` that is more readable and shorter exists.

It may be also useful to expand description with a note that this change may improve performance (as it would no longer be implied)

------

Other usual issue fields are not applicable - I spotted it during reviewing https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

### PR DESCRIPTION
**Pull request by anuja-joshi**
Moved `Performance/LstripRstrip` to `Style/LstripRstrip`, as per [#6637](https://github.com/rubocop-hq/rubocop/issues/6637)

### CODE REVIEW

**Comment by bbatsov** [comment]
I also wonder if we shouldn't rename this to `Style/Strip`. @rubocop-hq/rubocop-core Any thoughts?

**Comment by Drenmi** [comment]
Plus one for renaming. 👍

**Comment by bbatsov** [comment]
I'll do the renaming myself. 

@anuja-joshi Thanks!

**Comment by matkoniecz** [comment]
@anuja-joshi Thank you for implementing this! I opened #6871 ("promote Performance/RedundantSortBy to Style/RedundantSortBy") as there is at least one more cop that is worth rescuing before #5977 happens.

**Comment by bbatsov** [comment]
FYI - the removal of the performance cops is scheduled to happen 2 releases from now. Next release will deprecate them and point to the new gem. 0.68 is going to delete them.

**Pull request merged**
