### PR TITLE
Extract `ConfigStore#for_pwd`

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This PR extracts some duplicated logic into `ConfigStore#for_pwd`.

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by marcandre** [comment]
Instead of a new method, couldn't the argument be `pwd` by default?

**Comment by deivid-rodriguez** [comment]
You mean saying `for_dir` without arguments instead of `for_pwd`, right? That looks harder to understand to me, but I can change it.

**Comment by marcandre** [comment]
Yes, that's what I meant, but either way is fine by me.

**Comment by deivid-rodriguez** [comment]
If it looks fine either way to you, I think I strictly prefer my version :)

**Comment by bbatsov** [comment]
Shocker! 🤣

**Pull request merged**
