### PR TITLE
Refactor Lint/DuplicateCaseCondition cop with Set

### PR DESCRIPTION
**Pull request by fatkodima**

### CODE REVIEW

**Comment by koic** [comment]
I don't understand the benefits of merging this PR. It seems downside of keeping `git blame` away, and regression risk seems to be greater.

**Comment by fatkodima** [comment]
Simpler code?
cc @marcandre

**Comment by koic** [comment]
I value `git blame` for maintenance. The current code is fully maintainable.

**Comment by marcandre** [comment]
> > I don't understand the benefits of merging this PR.
> 
> Simpler code?

I agree, the resulting code is superior 👍

**Pull request merged**
