### PR TITLE
Self contained CircleCI config

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This PR makes the CircleCI config self-contained, so it doesn't depend on repo configuration that must be set in CircleCI UI.

As you can [see](https://circleci.com/gh/deivid-rodriguez/rubocop/1205), as opposed to #6220, build now uses two workers instead of 32.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@bbatsov You can remove the env variables from CircleCI's UI and it should still work the same.

**Comment by bquorning** [comment]
I can remove the ENV variables from Circle CI after this is merged in.

**Comment by bbatsov** [comment]
Please, do.

**Comment by bquorning** [comment]
Done

**Pull request merged**
