### PR TITLE
[Fix #8354] Fix Style/CaseLikeIf to handle regexp named captures

### LINKED ISSUE #8354: Autocorrect for Style/CaseLikeIf changes behaviour of regex match data
The rubocop auto-correct for the Style/CaseLikeIf cop had some unexpected behaviour when dealing with the ruby match operator in combination with if/elsif statements.
To be more precise, the match data object is not returned anymore after moving the regex condition to a `case` statement.

--------

## Expected behavior

The Style/CaseLikeIf cop takes the `=~` match operator into account.

## Actual behavior

The Style/CaseLikeIf cop autocorrect changed the behaviour of the code, which lead to faulty results and failing test's.

## Steps to reproduce the problem

**Before**
```
params[:command] = 'set-disable'
if params[:command] == 'remove'
  # do something
elsif %r{^set-(?<status>disable|enable)$} =~ params[:command]
  puts status
end
```
**Result**
`disable`

**After auto-correct**
```
params[:command] = 'set-disable'
case params[:command]
when 'remove'
  # do something
when /^set-(?<status>disable|enable)$/
  puts status
end
```
**Result**
`NameError (undefined local variable or method 'status' for main:Object)`

See also https://github.com/openSUSE/open-build-service/pull/9914/commits/6909ea77bad28fbb3db9cd214e359a9cfafa7e5b

## RuboCop version

```
frontend@3099cfde322d:/obs/src/api> rubocop -V
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.5.8 x86_64-linux-gnu)
```

### LINKED ISSUE #8541: Style/CaseLikeIf unsafe if conditionally executed code needs MatchData
Style/CaseLikeIf is unsafe in edge cases. It gives false positives if both:
- `if` or `elsif` includes a regular expression, and
- the code that's executed when the condition is true depends on something in the match other than the existence or numerical position of a match.
--------

## Expected behavior

I expect RuboCop to **not** generate a Style/CaseLikeIf offense.

## Actual behavior

RuboCop generates a Style/CaseLikeIf offense.

## Steps to reproduce the problem

Create an `if-elsif` where the `if` or `elsif` includes `=~` or `.match` and the conditionally executed code depends on something in the match other than true/false or the position of the match. 

In my case the problematic code was
```ruby
      if /^(?<yr>\d{4})$/ =~ val
        yyyymmdd([yr, 1, 1], [yr, 12, 31])
      elsif /^(?<yr>\d{4})-(?<mo>\d\d?)$/ =~ val
        yyyymmdd([yr, mo, 1], [yr, mo, 31])
      elsif /^(?<yr>\d{4})-(?<mo>\d\d?)-(?<day>\d\d?)$/ =~ val
        yyyymmdd([yr, mo, day], [yr, mo, day])
      elsif /^(?<yr1>\d{4})-(?<yr2>\d{4})$/ =~ val
        yyyymmdd([yr1, 1, 1], [yr2, 12, 31])
      elsif /^(?<yr1>\d{4})-(?<mo1>\d\d?)-(?<yr2>\d{4})-(?<mo2>\d\d?)$/ =~ val
        yyyymmdd([yr1, mo1, 1], [yr2, mo2, 31])
      elsif /^(?<yr1>\d{4})-(?<mo1>\d\d?)-(?<dy1>\d\d?)-
             (?<yr2>\d{4})-(?<mo2>\d\d?)-(?<dy2>\d\d?)$/x =~ val
        yyyymmdd([yr1, mo1, dy1], [yr2, mo2, dy2])
      elsif /^(?<mo>\d\d?)$/ =~ val
        mmdd([mo, 1], [mo, 31])
      elsif /^(?<mo1>\d\d?)-(?<mo2>\d\d?)$/ =~ val
        mmdd([mo1, 1], [mo2, 31])
      elsif /^(?<mo1>\d\d?)-(?<dy1>\d\d?)-(?<mo2>\d\d?)-(?<dy2>\d\d?)$/ =~ val
        mmdd([mo1, dy1], [mo2, dy2])
      else
        raise BadDateRangeError.new(var: var, val: val)
      end
```
Each `if` or `elsif` has a named capture group that's used in the following conditionally executed code. 
But if you re-write the above as a `case` statement, , e.g.:
```ruby
      case val
      when /^(?<yr>\d{4})$/ 
        yyyymmdd([yr, 1, 1], [yr, 12, 31])
      ...
      end
```
then the named capture group (`yr`)is not available to the conditionally executed code.
This is due to the fact that `when` uses `===`, which is not equivalent to the `=~` used in `if` and `elsif`. Compare
```ruby
$ /(?<yr>\d{4})/ === "20190815"; yr
true
nil
```
with
```ruby
$ /(?<yr>\d{4})/ =~ "20190815"; yr
0
"2019"
```

Comment:
Some options:
1. Mark `Style/CaseLikeIf` as unsafe.
2. Make `Style/CaseLikeIf` safe by catching all the edge cases. Strikes me as very difficult or impossible to accomplish.
3. Make `Style/CaseLikeIf` safe by ignoring conditionals where an `if` or `elsif` includes `=~` or `.match`. (I don't like this. `Style/CaseLikeIf` does work for the most common regex use case, and I wouldn't like to throw that away.)

## RuboCop version
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.6.6 x86_64-linux)

### PR DESCRIPTION
**Pull request by dmytro-savochkin**
Fixes #8354.
Fixes #8541.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by marcandre** [comment]
If #8510 is merged first, it would be best to use that instead of doing the parsing with a regexp

**Comment by bbatsov** [comment]
As it's merged now, I guess we should update this PR.

**Comment by dmytro-savochkin** [comment]
> As it's merged now, I guess we should update this PR.

updated

**Comment by koic** [comment]
@dmytro-savochkin This change looks good to me. Can you rebase and update the changelog with the latest master branch? I'm sorry for taking up your time 💦

**Comment by dmytro-savochkin** [comment]
> @dmytro-savochkin This change looks good to me. Can you rebase and update the changelog with the latest master branch? I'm sorry for taking up your time 💦

@koic, no problem, updated.

**Comment by koic** [comment]
@dmytro-savochkin Thank you!

**Pull request merged**
