### PR TITLE
CI: Only pushes to master should trigger builds

### PR DESCRIPTION
**Pull request by marcandre**
**Replace this text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
* [ ] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Why so? Seems a bit weird to wait for a `master` merge to see something's broken on Windows. (unless I'm misunderstanding the change)

**Comment by marcandre** [comment]
The CI was running when pushing (and force-repushing) branches for PRs, in addition to the PR.

This way, the CI runs whenever a PR is created / updated, and for pushes to `master` (as a precaution in case the merge is no longer green, or if we push directly to `master`).

**Comment by bbatsov** [comment]
I'm still a bit confused, but I trust you did the right thing. 😄

**Comment by marcandre** [comment]
Well, it is confusing. So there are three reductions:
- no double run for tags. [Look for "Cut 1.3" here](https://github.com/rubocop-hq/rubocop/actions?query=event%3Apush)
- no double run if a committer pushes to this repo (like I do for chained PRs)
- but mainly, everyone that has a fork was also running the CI when they were pushing their own branches to their repo (unless they turned it off). For example [all these builds](https://github.com/marcandre/rubocop/actions) were triggered from my repo, while there are the equivalent builds from this repo because of the pull requests I make.

I don't understand it's not the default / better documented, and also why actions are run by default for forks (3rd point above).

**Comment by bbatsov** [comment]
Now I get it! Thanks!

It's a weird default indeed. Now I have some memories that in the past we did similar changes for CircleCI. One day we should probably move everything to GHA for consistency, but that's not a big deal.

**Pull request merged**
