### PR TITLE
[Fix #5184] Add new multiline element line break cops

### LINKED ISSUE #5184: Enforce one parameter per line when method parameters span more than one line
Not sure if this should be considered a bug in the `Layout/AlignParameters` cop, a new style for it, or a separate cop, but I'd certainly like this to be signaled as a style offense.

Given the following code

```ruby
a(1,
  2, 3,
  4)
```

## Expected behavior

I would expect rubocop to tell me

```
Layout/AlignParameters: Align the parameters of a method call if they span more than one line.
```

for the third parameter, since it's not aligned with the rest of them.

## Actual behavior

No offenses are registered.

## Steps to reproduce the problem

```shell
$ echo "
> a(1,
>   2, 3,
>   4)" | bundle exec rubocop --stdin hola.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by maxh**
Fixes https://github.com/rubocop-hq/rubocop/issues/5184 by adding support for autocorrecting cops that ensure that individual elements in multiline arrays, hashes, and method calls each start on separate lines.

```rb
# bad:
[
  a, b,
  c
]

# good:
[
  a,
  b,
  c
]
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by TSMMark** [comment]
This looks great! Thank you for doing this. I managed to find some time today to run a mass auto-correct from this branch on our medium sized ruby codebase. It works very well!

I did notice one thing, which I'm not sure if it is intended or not. Ptal:

```ruby
# bad:
hash[:foo] = {
  :bar => true,
  :baz => false,
}
```

```ruby
# good:
hash[:foo] =
  {
    :bar => true,
    :baz => false,
  }
```

I'm fine with this ruling but wanted to point it out in case it was unintentional.

**Comment by maxh** [comment]
Thanks for trying it out! I've seen that as well. Just wrote some quick unit tests locally and confirmed this cop is working as intended:

image

I think it might be due to unexpected interaction during autocorrect with this cop:

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/FirstHashElementLineBreak

Two questions:

1) If you disable that cop, does the issue still appear? My hypothesis: no.
2) If you manually fix it to the "bad" case, does the code get autocorrected back to the good? My hypothesis: no, the "bad" is allowed after manual fixing.

**Comment by TSMMark** [comment]
@maxh I will have to try that when I get a chance, but if your local unit test passes then I'm confident you're right. Good to know thank you

**Comment by deivid-rodriguez** [comment]
Thanks so much for adding this @maxh, I really like this new family of cops! :)

**Comment by bbatsov** [comment]
Nicely done! And sorry for the slow turnaround here!

**Pull request merged**
