### PR TITLE
[Fix #7564] Drop dependency on jaro_winkler gem

### LINKED ISSUE #7447: Installation fails on Ubuntu 18.04 running Ruby 2.6.3
The `jaro_winkler` gem is also failing to install and so I am not sure if the issue is with that gem or with Rubocop but wanted to report it. Rubocop installs just fine if I revert back to Ruby 2.5.3.

```>> gem install rubocop
Building native extensions. This could take a while...
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.

    current directory: /home/sjayanna/.rvm/gems/ruby-2.6.3/gems/jaro_winkler-1.5.3/ext/jaro_winkler
/home/sjayanna/.rvm/rubies/ruby-2.6.3/bin/ruby -I /home/sjayanna/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0 -r ./siteconf20191018-14011-1xlq2d.rb extconf.rb
creating Makefile

current directory: /home/sjayanna/.rvm/gems/ruby-2.6.3/gems/jaro_winkler-1.5.3/ext/jaro_winkler
make "DESTDIR=" clean

current directory: /home/sjayanna/.rvm/gems/ruby-2.6.3/gems/jaro_winkler-1.5.3/ext/jaro_winkler
make "DESTDIR="
compiling adj_matrix.c
gcc: error: unrecognized command line option '-Wduplicated-cond'
gcc: error: unrecognized command line option '-Wmisleading-indentation'
gcc: error: unrecognized command line option '-Wrestrict'
gcc: error: unrecognized command line option '-Wimplicit-fallthrough=0'
Makefile:243: recipe for target 'adj_matrix.o' failed
make: *** [adj_matrix.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/sjayanna/.rvm/gems/ruby-2.6.3/gems/jaro_winkler-1.5.3 for inspection.
Results logged to /home/sjayanna/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/jaro_winkler-1.5.3/gem_make.out```

### LINKED ISSUE #7564: Installation Error on MacOS
RuboCop doesn't install.
--------

## Expected behavior

RuboCop installs

## Actual behavior

Console outputs:
```
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191212-97928-1pj6l4t.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
```

## Steps to reproduce the problem

New macOS version 10.14.5, run in terminal:
`sudo gem install rubocop`

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.77.0 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by buehmann**
Ruby 2.3 and later ship with the `did_you_mean` gem, which includes a
JaroWinkler implementation.

So there is no need to depend on the `jaro_winkler` gem that people have
had trouble installing lately.

Fixes #7564 and fixes #7447.

### CODE REVIEW

**Comment by buehmann** [comment]
Hmm … will look into the JRuby failures later.

**Comment by buehmann** [comment]
This was a nice idea, but it is too difficult to make this work across all Ruby versions. To be revisited once RuboCop drops support for Ruby 2.3.

**Comment by rupertohpen** [comment]
> This was a nice idea, but it is too difficult to make this work across all Ruby versions. To be revisited once RuboCop drops support for Ruby 2.3.

Having wasted another hour of my life trying to install rubocop in a container and banging my head against the jaro dependency, I would say that if a nice idea is the difference between being able to install rubocop and not, then it's not just a nice idea anymore.  If it's that difficult, please focus on dropping the ruby 2.3 support. This evening would be nice, so I can finish this bit or work.

**Comment by koic** [comment]
I’m aware of this issue and plan to determine and drop support for Ruby 2.3 in the near future. But now is not the time.

**Pull request closed without merging**
