### PR TITLE
Do not show warning for inherit_mode cop parameter

### PR DESCRIPTION
**Pull request by maxh**
This disables (what I believe to be) an untrue warning. Currently, when running:

`rubocop --auto-gen-config`

I see the following warning:

Warning: unrecognized parameter Lint/AmbiguousBlockAssociation:inherit_mode found in .rubocop.yml

The parameter is working as intended according to the documentation [here](https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md#merging-arrays-using-inherit_mode), however. We believe the warning is spurious. With this change applied, the warning does not appear. 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by Drenmi** [comment]
Thanks @maxh! You'll need to rebase and fix the merge conflict in `CHANGELOG`. 🙇

**Comment by maxh** [comment]
>Thanks @maxh! You'll need to rebase and fix the merge conflict in CHANGELOG. 🙇

done!

**Comment by Drenmi** [comment]
LGTM @bbatsov.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
