### PR TITLE
Add new `Layout/SpaceBeforeBrackets` cop

### PR DESCRIPTION
**Pull request by koic**
Follow https://github.com/rubocop-hq/ruby-style-guide/pull/856.

This PR adds new `Layout/SpaceBeforeBrackets` cop.

```ruby
# bad
collection [index_or_key]

# good
collection[index_or_key]
```

This cop is marked as unsafe because it can occur false positives for `do_something [this_is_an_array_literal_argument]` that take an array without parentheses as an argument.

I noticed this issue below.
https://github.com/rsim/oracle-enhanced/pull/2076/files#diff-0d21136da5aee9b25213dcf874f62418fa24a06a90237e069642a5af54e7b2efL494-R494

**Replace this text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks!

**Comment by eamonn-webster** [comment]
Is it meant to apply in the following case 
```
paths %w[lib]
```

**Comment by bbatsov** [comment]
This case will be ignored, unless `paths` is resolved to some variable identifier.

**Comment by eamonn-webster** [comment]
Just seen the fix https://github.com/rubocop-hq/rubocop/pull/9291.

**Pull request merged**
