### PR TITLE
[Fix #7979] Add runtime dependency for did_you_mean

### LINKED ISSUE #7979: uninitialized constant DidYouMean::SpellChecker
TLDR: In c92a591, the name similarity module started using `DidYouMean::SpellChecker` but this gem is not explicitly listed as a dependency.

--------

## Expected behavior

Rubocop does not crash. We get an offense such as:
`Unnecessary disabling of Lint/SuperCoolCop (did you mean Layout/SuperCoolCop?)`

## Actual behavior

We see the following error when running Rubocop:
```
Uninitialized constant DidYouMean::SpellChecker
--
  | /var/www/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:18:in `find_similar_names'
  | /var/www/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:9:in `find_similar_name'
```

## Steps to reproduce the problem

Add a magic comment to disable a cop that does not actually exist. E.g. `# rubocop:disable Lint/SuperCoolCop`

## RuboCop version

```
$ bundle exec rubocop -V
0.83.0 (using Parser 2.7.1.2, running on ruby 2.6.6 x86_64-darwin19)
```

### PR DESCRIPTION
**Pull request by geshwho**
**Replace this text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I don't think that should needed for a gem bundled with Ruby. It also seems that most people didn't run into such an issue. @koic Any idea what might be causing such a problem?

**Comment by geshwho** [comment]
@bbatsov, I [noticed yesterday](https://github.com/rubocop-hq/rubocop/issues/7979#issuecomment-629438983) that according to the docs out should be included with Ruby 2.3+. Looks like at least one other person came across this in #7979.

Also in my case, I saw this issue in CI not my local machine so I'm trying to gather more information on that environment.

**Comment by koic** [comment]
RuboCop Rails had a similar problem, but hasn't got a solution to it yet.
https://github.com/rubocop-hq/rubocop-rails/pull/243

AFAIK, Ruby has enable and disable options for did_you_mean.

```console
% ruby -v
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-darwin17]

% ruby --enable-did-you-mean -e 'DidYouMean'
% ruby --disable-did-you-mean -e 'DidYouMean'
-e:1:in `<main>': uninitialized constant DidYouMean (NameError)
```

or

```console
% RUBYOPT='--enable-did-you-mean' ruby -e 'DidYouMean'
% RUBYOPT='--disable-did-you-mean' ruby -e 'DidYouMean'
-e:1:in `<main>': uninitialized constant DidYouMean (NameError)
```

However, I'm not sure about that is affecting the problem... 🤔

**Comment by koic** [comment]
> I don't think that should needed for a gem bundled with Ruby.

And I agree with this.

**Comment by bquorning** [comment]
I just ran into this issue as well, but like you I haven’t figured out what the underlying problem is.

@koic I didn’t know about the enable/disable option for this feature, but judging from these different error messages it’s not the problem we are looking for:

```
ruby -e 'puts DidYouMean::SpellChecker'
-e:1:in `<main>': uninitialized constant DidYouMean::SpellChecker (NameError)

RUBYOPT='--disable-did-you-mean' ruby -e 'puts DidYouMean::SpellChecker'
-e:1:in `<main>': uninitialized constant DidYouMean (NameError)
```

**Comment by bquorning** [comment]
Sorry. Let’s keep the discussion in #7979 from here on.

**Comment by mosaicin** [comment]
rails server
/home/evgruby/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/error.rb:105: warning: constant DidYouMean::SPELL_CHECKERS is deprecated
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
/home/evgruby/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/error.rb:105: warning: constant DidYouMean::SPELL_CHECKERS is deprecated
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/home/evgruby/.rvm/gems/ruby-2.7.1/gems/thor-1.1.0/lib/thor/error.rb:105: warning: constant DidYouMean::SPELL_CHECKERS is deprecated
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Traceback (most recent call last):

**Comment by koic** [comment]
It looks like a Thor error, not a RuboCop error. JFYI, https://github.com/rails/thor/pull/761 for fix to the issue is already open.

**Comment by mosaicin** [comment]
thanks a lot.

**Pull request closed without merging**
