### PR TITLE
Optimize code length calculation

### PR DESCRIPTION
**Pull request by fatkodima**
On `rubocop`s own codebase:
```
$ bin/rubocop-profile  --cache false --only Metrics
$ rake prof:slow_cops
```

### Before
```
  1* 249  (   22.4%)  RuboCop::Cop::Metrics::ModuleLength#on_module
     160  (   14.4%)  RuboCop::Cop::MethodComplexity#on_def
  2* 144  (   13.0%)  RuboCop::Cop::Metrics::MethodLength#on_def
     134  (   12.1%)  RuboCop::Cop::MethodComplexity#on_def
  3* 124  (   11.2%)  RuboCop::Cop::Metrics::ClassLength#on_class
     106  (    9.5%)  RuboCop::Cop::MethodComplexity#on_def
  4*  70  (    6.3%)  RuboCop::Cop::Metrics::BlockLength#on_block
      36  (    3.2%)  RuboCop::Cop::Metrics::ParameterLists#on_args
      30  (    2.7%)  RuboCop::Cop::MethodComplexity#on_block
      19  (    1.7%)  RuboCop::Cop::MethodComplexity#on_block
      16  (    1.4%)  RuboCop::Cop::MethodComplexity#on_block
      12  (    1.1%)  RuboCop::Cop::Metrics::MethodLength#on_block
       4  (    0.4%)  RuboCop::Cop::Metrics::MethodLength#on_def
       4  (    0.4%)  RuboCop::Cop::Metrics::ClassLength#on_casgn
       1  (    0.1%)  RuboCop::Cop::Metrics::ModuleLength#on_casgn
       1  (    0.1%)  RuboCop::Cop::MethodComplexity#on_def
       1  (    0.1%)  RuboCop::Cop::MethodComplexity#on_def
```

### After
```
     182  (   21.3%)  RuboCop::Cop::MethodComplexity#on_def
     162  (   19.0%)  RuboCop::Cop::MethodComplexity#on_def
     102  (   12.0%)  RuboCop::Cop::MethodComplexity#on_def
  2*  98  (   11.5%)  RuboCop::Cop::Metrics::MethodLength#on_def
  1*  67  (    7.9%)  RuboCop::Cop::Metrics::ModuleLength#on_module
      53  (    6.2%)  RuboCop::Cop::MethodComplexity#on_block
  3*  44  (    5.2%)  RuboCop::Cop::Metrics::ClassLength#on_class
      38  (    4.5%)  RuboCop::Cop::Metrics::ParameterLists#on_args
      26  (    3.0%)  RuboCop::Cop::MethodComplexity#on_block
  4*  23  (    2.7%)  RuboCop::Cop::Metrics::BlockLength#on_block
   *  22  (    2.6%)  RuboCop::Cop::Metrics::MethodLength#on_block
      20  (    2.3%)  RuboCop::Cop::MethodComplexity#on_block
       4  (    0.5%)  RuboCop::Cop::Metrics::ClassLength#on_casgn
       3  (    0.4%)  RuboCop::Cop::Metrics::ModuleLength#on_casgn
       3  (    0.4%)  RuboCop::Cop::MethodComplexity#on_def
       2  (    0.2%)  RuboCop::Cop::Metrics::MethodLength#on_def
       1  (    0.1%)  RuboCop::Cop::MethodComplexity#on_def
       1  (    0.1%)  RuboCop::Cop::MethodComplexity#on_def
```

### CODE REVIEW

**Comment by marcandre** [comment]
It's great that you have sped them up. Are you going to work on them some more? If not, I'll make them even faster 😃

**Comment by fatkodima** [comment]
I have done some work on optimizing `Style` and `Lint` cops, but those are not very dramatic. The most greedy are `Layout` cops, but them are a bit involved. Will open 2 more PRs today or tomorrow.

> Are you going to work on them some more? If not, I'll make them even faster 😃

Are you talking about `Metrics` cops or in general? Do you have suggestions? 😄

**Comment by marcandre** [comment]
> Are you talking about `Metrics` cops or in general? Do you have suggestions? 😄

The `Metrics/XxxLength` ones. They go through extensive calculations to remove some lines (empty and whatnot). I did not check the algorithm for that. But one clear optimization is that it's completely useless to do this the the range including the lines that don't count is already small. The calculator should have a `if_above` parameter, if the node's expression spans less than `if_above`, just return that. Or shortcircuit before calling the calculator.

**Comment by fatkodima** [comment]
Are you talking about something like this https://github.com/rubocop-hq/rubocop/pull/8356/files#diff-d20d7272bb02c47063866ed46a4500eaR34-R35 ?

**Comment by marcandre** [comment]
> Are you talking about something like this https://github.com/rubocop-hq/rubocop/pull/8356/files#diff-d20d7272bb02c47063866ed46a4500eaR34-R35 ?

🤣 yes, exactly, I didn't see it! You should create the calculator *after* that check though :-)

**Comment by marcandre** [comment]
BTW, ` --cache false` is no longer necessary in `master`

**Comment by bbatsov** [comment]
:rocket:

**Pull request merged**
