### PR TITLE
Add new HeredocMethodCallPosition cop

### PR DESCRIPTION
**Pull request by maxh**
A small opportunity for a cop discovered while working on https://github.com/rubocop-hq/rubocop/pull/6988:

bad:
```rb
<<-SQL
  bar
SQL
.strip_indent
```

good:
```
<<-SQL.strip_indent
  bar
SQL
```
-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Isn't this actually a lint cop?

**Comment by maxh** [comment]
>Isn't this actually a lint cop?

It very well could be! I just renamed and repushed. The distinction between layout and lint has always been a bit unclear to me. This is the best documentation I could find on the difference:

https://rubocop.readthedocs.io/en/latest/basic_usage/

Curious what you think.

**Comment by bbatsov** [comment]
> The distinction between layout and lint has always been a bit unclear to me.

The basic distinction is necessity vs preference. Lint cops indicate a potential mistake, while layout cops deal with preferred layout. Does this make sense?

**Comment by bbatsov** [comment]
Btw, for this particular cop it's really hard to decide - it can easily have been a style cop as well, but I feel that placing the method after the heredoc introduces a significant potential for an error if someone decides to bring this one line up.

**Comment by bbatsov** [comment]
One more thing - please, add a rule about this to the Ruby style guide. I think that'd be a nice addition there.

**Comment by maxh** [comment]
Thanks for the quick review!

>The basic distinction is necessity vs preference. Lint cops indicate a potential mistake, while layout cops deal with preferred layout. Does this make sense?

Yep!

>Btw, for this particular cop it's really hard to decide - it can easily have been a style cop as well, but I feel that placing the method after the heredoc introduces a significant potential for an error if someone decides to bring this one line up.

+1

>add a rule about this to the Ruby style guide

https://github.com/rubocop-hq/ruby-style-guide/pull/745

**Pull request merged**
