### PR TITLE
Fix false positive in `Style/RedundantSelf` cop with nested `self` access

### PR DESCRIPTION
**Pull request by marcotc**
This PR fixes the following false positive:
```ruby
a = self.a || b
```
which currently returns:
```
file.rb:1:5: C: Style/RedundantSelf: Redundant self detected.
a = self.a || b
    ^^^^^^
```

This is a false positive, as `self.a` cannot be changed to `a` while keeping the same semantics. Changing it to `a` would effectively make the left-hand side of this `or` statement always `nil`, as `a` has just been declared and still doesn't have a value assigned.

This happens because the logic on `redundant_self.rb` does not check for nested statements (in the example, `self.a` is nested node inside an `or` node).
This PR adds an ancestor search, starting from `self.a`, to try to find if any of its ancestors are associated with a local variable to name `a`. The changes introduced work for any level of nesting.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.

**Comment by marcotc** [comment]
Thank you, @bbatsov, a simple rebase did the trick. Let me know if there's any additional feedback!

**Comment by bbatsov** [comment]
@marcotc I totally dropped the ball on you. Sorry! Can you rebase again and move the changelog entry to the unreleased section?

**Review by bbatsov — APPROVED** [review]

**Comment by marcotc** [comment]
Sorry for not rebasing earlier, @bbatsov, I was on vacation recently. Thank you very much on merging it!

Also, huge congratulations on shipping 1.0!

**Pull request merged**
