### PR TITLE
[Fix #4882] Use `IndentationWidth` of `Layout/Tab` for other cops

### LINKED ISSUE #4882: `IndentationWidth` from disabled `Layout/Tab` for `Metrics/LineLength` calculations
I think, the new `IndentationWidth` from `Layout\Tab` cop should be taken into account for `Metrics\LineLenght` cop (especially when `Enabled: false`).

--------

## Expected behavior

If I have config:

```yaml
Layout/IndentationWidth:
  Width: 1
Layout/Tab:
  Enabled: false
  IndentationWidth: 2

Metrics/LineLength:
  Max: 7 # for simplified example
```

and code:

```ruby
def foo
->abcdef # 1 tab and 6 letters
end
```

Then I should indent the code with one tab, but which is calculating as 2 spaces for other cops (especially for `Metrics/LineLength`).

So, 1 tab with width equal to 2 spaces, plus 6 letters = 8 symbols (greater then `Max` from `Metrics/LineLength`).

There is should be offense from `Metrics/LineLength` cop.

## Actual behavior

There are no warnings.

## Steps to reproduce the problem

In "Expected behavior".

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by AlexWayfer**
* Metrics/LineLength
* Style/IfUnlessModifier

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I agree with the overall spirit of the change, but I wonder if this is the best way to share the common config between the few cops. Many we can pull up some config values under `CommonSettings` or something like this instead?

**Comment by AlexWayfer** [comment]
> I agree with the overall spirit of the change, but I wonder if this is the best way to share the common config between the few cops. Many we can pull up some config values under CommonSettings or something like this instead?

Why don't you like `Layout/Tab` => `IndentationWidth`?

**Comment by bbatsov** [comment]
Because from a user perspective I find it extremely odd that one cop would be configuring the behavior of a few others. That's never exactly transparent, and it's often quite confusing. We have such dependencies in the code even now, but it's usually for cops where the dependencies between they are quite obvious - I'd normally never go looking for a base indentation width setting in some cop converting tabs into spaces.

**Comment by bbatsov** [comment]
Got it. I'm on the fence about this. @jonas054 What do you think?

**Comment by jonas054** [comment]
:+1: I think the change is good.

We can assume that most people use only spaces for indentation and alignment, so it won't cause any problems for them. And the change does provide some rudimentary support in RuboCop for people who like the Smart Tabs idea (tabs for indentation and spaces for alignment).

Down the road, we might like to add `EnforcedStyle: smart_tabs` to `Layout/Tab` so it can check that there are no tabs after space, and a default `EnforcedStyle: no_tabs` acting like today.

**Comment by bbatsov** [comment]
> Down the road, we might like to add EnforcedStyle: smart_tabs to Layout/Tab so it can check that there are no tabs after space, and a default EnforcedStyle: no_tabs acting like today.

That's a great idea!

**Comment by bbatsov** [comment]
@AlexWayfer The documentation of the affected cops has to be updated to mention the new behaviour and the changelog has to be moved to the current release.

**Comment by AlexWayfer** [comment]
> and the changelog has to be moved to the current release

Done.

> @AlexWayfer The documentation of the affected cops has to be updated to mention the new behaviour 

I didn't find any information about docs changing in the `CONTRIBUTION.md` (should I edit anything in the `manual/` dir?), but I changed comments above the code of the affected cops.

**Comment by jonas054** [comment]
@AlexWayfer It's not mentioned in `CONTRIBUTION.md`, but in the check list of the PR you have "Run `rake default` or `rake parallel`." If there are any changes in cop documentation, you will get changes in generated manual files, that you need to commit.

There are currently failures in the build, BTW.

**Comment by AlexWayfer** [comment]
> @AlexWayfer It's not mentioned in CONTRIBUTION.md, but in the check list of the PR you have "Run rake default or rake parallel." If there are any changes in cop documentation, you will get changes in generated manual files, that you need to commit.

Thank you!

> There are currently failures in the build, BTW.

That's strange. OK, I fixed.

-----

Wat?

image

**Comment by koic** [comment]
@AlexWayfer I opened a PR #6003 to fix for `Layout/ClosingHeredocIndentation` false positive.

**Comment by AlexWayfer** [comment]
> @AlexWayfer I opened a PR #6003 to fix for Layout/ClosingHeredocIndentation false positive.

Thank you, I'll wait merging for rebase.

**Comment by AlexWayfer** [comment]
I was on vacation, now I've rebased this branch and tests passed.

(thanks, @koic)

**Pull request merged**
