### PR TITLE
Update Performance/Sample to register offenses when shuffle is followed with at or slice

### PR DESCRIPTION
**Pull request by rrosenblum**
A few of the recent Performance cops have support for `at` and `slice`. This adds the same support to `Performance/Sample`.

### CODE REVIEW

**Comment by rrosenblum** [comment]
It looks like build is failing because Travis CI doesn't know about `jruby-9.2.0.0`. The same failure is happening in master. I'm not sure why this would have started failing recently.

**Comment by koic** [comment]
Yes. JRuby build errors on Travis CI are reported below. I think that changes in this PR are not related to this build error.
https://github.com/travis-ci/travis-ci/issues/9826

**Comment by bbatsov** [comment]
Nice update! Don't forget to update this spec in `rubocop-performance` as well.

**Comment by rrosenblum** [comment]
I didn't know that `rubocop-performance` had been created yet. I'll update that code as well.

What else needs to be done to `rubocop-performance` and `rubocop` to make use of separate gems?

**Pull request merged**
