### PR TITLE
Add new `Lint/DuplicateElsifCondition` cop

### PR DESCRIPTION
**Pull request by fatkodima**
This cop checks for duplicated conditions in `elsif`s. This is almost definitely a programmer mistake due to copy-paste, refactoring, etc.

```ruby
# bad
if x == 1
  do_something
elsif x == 1
  do_something_else
end

# good
if x == 1
  do_something
elsif x == 2
  do_something_else
end
```

This cop is in addition to existing `Lint/DuplicateCaseCondition`.

### CODE REVIEW

**Comment by bbatsov** [comment]
Seems to me this should be a Lint cop.

**Comment by bbatsov** [comment]
Seems it's a Style cop only in the PR description and the commit message. :-)

**Comment by fatkodima** [comment]
Haha, yes, it is a bad copy-paste 😄

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
