### PR TITLE
[Fix #6183] ConfigurableNaming FORMATS constant now accepting utf-8 characters in snake_case method names

### LINKED ISSUE #6183: Misreporting method naming should be snake_case for utf-8 method names
## Expected behavior

I expect the following code snippet to not trigger method name snake_case cop.

```ruby
def ação(param)
end
```

## Actual behavior

Rubocop is (probably) misinterpreting utf-8 method names as non snake_case method names.

## Steps to reproduce the problem

Rubocop the above code snippet.

## RuboCop version

```
$ rubocop -V
0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by martincabrera**
Fix ConfigurableNaming FORMATS constant accepting utf-8 characters in snake_case method names.

Followed [Wikipedia List of unicode characters](https://en.wikipedia.org/wiki/List_of_Unicode_characters) and added specs for lowercase Latin alphabet, Latin-1 Supplement, Latin Extended-A & Latin Extended-B characters.

***

 - [x] Wrote good commit messages.
  - [x] Commit message starts with [Fix #issue-number] (if the related issue exists).
  - [x] Feature branch is up-to-date with master (if not - rebase it).
  - [x] Squashed related commits together.
  - [x] Added tests.
  - [x]  Added an entry to the Changelog if the new code introduces user-observable changes. See changelog entry format.
  - [x]  The PR relates to only one subject with a clear title
and description in grammatically correct, complete sentences.
  - [x] Run rake default. It executes all tests and RuboCop for itself, and generates the documentation.

### CODE REVIEW

**Comment by bbatsov** [comment]
Hmm, the problem is we intentionally avoided those in the past, as generally in programming identifiers should ideally be constrained to ASCII. I'm open to making this configurable, but I generally don't see the point in using non-ascii characters for identifiers, as this also implies you're not using English for them.

**Comment by martincabrera** [comment]
OK, it didn't make much sense to me having non ascii characters in method names but I wanted to contribute and someone flagged it as bug...

**Comment by deivid-rodriguez** [comment]
Maybe not a good practice, but it's [pretty cool](https://github.com/mperham/sidekiq/blob/99922ca4ad3ba8be279c82d6def986575e0f4214/lib/sidekiq/launcher.rb#L65-L71) :smile:.

**Comment by martincabrera** [comment]
Hi @Drenmi 

It will take a bit to remember the stuff I did, but I am happy to have a look at it!

**Comment by Drenmi** [comment]
Thank you, @martincabrera! ❤️

**Comment by bbatsov** [comment]
I'm closing this PR due to no recent activity. Feel free to re-open it if you ever come back to it.

**Pull request closed without merging**
