### PR TITLE
[Fix #8499] Fix Style/IfUnlessModifier to prevent offense when first-line comment and code after end block

### LINKED ISSUE #8499: Wrong correction in Style/IfUnlessModifier with first-line comment and code after the end block on the same line
I think `Style/IfUnlessModifier` doesn't correctly handle the case when there is a first-line comment (right after the `if` keyword) AND some code right after the `end` keyword. If you correct this code with `rubocop -a` it would put the comment right after the `end` keyword, before the code that was there previously. This basically makes the code invalid after correction.

This probably can be better seen in the example below.

I think in such a case we should stop auto-correction because it's pretty non-deterministic: where would that comment should go? Did it belong to the if-end condition? In this case it should go right after it, before the next code. But that's impossible in a single-line modifier form, unless we use these `/* comments */` but we probably wouldn't want to do this, so better not to auto-correct.

I can provide a PR if it seems right.

--------

## Steps to reproduce the problem

We have file `test.rb` with the following code:

```
[
  1, if foo # this is due to ...
       2
     end, 3
]
```

We run `rubocop test.rb --only Style/IfUnlessModifier -a`.

## Actual behavior

```
[
  1, (2 if foo) # this is due to ..., 3
]
```

## Expected behavior

Everything stays the same and no offense is given (I think it's the right way):
```
[
  1, if foo # this is due to ...
       2
     end, 3
]
```
or somehow it's fixed to
```
[
  1, (2 if foo), 3 # this is due to ...
]
```
but in this case the comment is in the wrong place, or it's fixed to
```
[
  1, (2 if foo) /* # this is due to ... */, 3 
]
```
but we probably don't want to use this syntax for comments.

## RuboCop version

0.89.0 (using Parser 2.7.1.4, rubocop-ast 0.2.0, running on ruby 2.5.1 x86_64-darwin18)

### PR DESCRIPTION
**Pull request by dmytro-savochkin**
Fixes #8499.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by marcandre** [comment]
I'd love to approve this PR, but there are many issues with `IfUnlessModifier` and `WhileUntilModifier`; ideally resolving this issue would be part of a bigger refactor. If you are not willing to tackle that, than the minimum acceptable is to add a corresponding test to `WhileUntilModifier`; for example the `first_line_comment` method in the module you are tweaking is redefined for `IfUnless` but not `WhileUntil`... I wish I had to time to look at all this myself.

**Comment by dmytro-savochkin** [comment]
> I'd love to approve this PR, but there are many issues with `IfUnlessModifier` and `WhileUntilModifier`; ideally resolving this issue would be part of a bigger refactor. If you are not willing to tackle that, than the minimum acceptable is to add a corresponding test to `WhileUntilModifier`; for example the `first_line_comment` method in the module you are tweaking is redefined for `IfUnless` but not `WhileUntil`... I wish I had to time to look at all this myself.

Well, actually I was thinking about handling `WhileUntilModifier` too. But later, not in this ticket.

And to be honest, I don't really think `IfUnlessModifier` and `WhileUntilModifier` are that much similar. They differ in the fact that `if/unless` constructs return something meaningful while `while/until` always return nil. Because of that people use `if` in assignment, in arrays, in hashes, etc, while no one usually uses `while` like that
```
[
  1, while foo # this is due to ...
       do_something
     end, 3
]
```

because what for? It would just return nil, no matter what happens inside the loop.

But still, I agree that something must be done with `WhileUntilModifier`, but definitely not in this PR. That's why there is a separate issue for that problem: https://github.com/rubocop-hq/rubocop/issues/8281.

**Comment by marcandre** [comment]
> It would just return nil, no matter what happens inside the loop.

That is a good point, but not completely accurate... `while true; break 42; end` returns 42.


Sorry if I wasn't clear: this PR is probably fine as is, but without a corresponding test in `WhileUntilModifier`, it's difficult for me to see the effect of the change on the module it shares, especially since they don't share the implementation of `first_line_comment` (which seems like a code smell).

**Comment by dmytro-savochkin** [comment]
> That is a good point, but not completely accurate... `while true; break 42; end` returns 42.
> 
> Sorry if I wasn't clear: this PR is probably fine as is, but without a corresponding test in `WhileUntilModifier`, it's difficult for me to see the effect of the change on the module it shares, especially since they don't share the implementation of `first_line_comment` (which seems like a code smell).

Ah, got it now. Updating the code.

**Comment by dmytro-savochkin** [comment]
@marcandre 
Is there any chance this PR can be approved? :)

**Comment by bbatsov** [comment]
@dmytro-savochkin I'm fine with the proposed change. It'd be nice if you updated the cop examples, so it's clear to users we're taking the comments into account.

**Comment by dmytro-savochkin** [comment]
@bbatsov, updated the examples.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
