### PR TITLE
Allow `#ruby` for Ruby version comment style on `LeadingCommentSpace`

### PR DESCRIPTION
**Pull request by cetinajero**
This PR removes the offense for comments that starts with `#ruby` as this style is
a valid syntax to write Ruby versions in `Gemfile` that can be used with [bundler, RVM, and others][1].

Example:

```ruby
  # Specific version (comment) will be used by RVM
  #ruby=2.7.0
  #ruby-gemset=myproject
  ruby '~> 2.7.0'
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://rvm.io/workflow/projects#project-file-gemfile

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm fine with adding this, but with a related configuration option. I don't want to introduce a performance penalty for people who are not using this. The description of the cop should also be expanded to reflect this.

**Comment by cetinajero** [comment]
Thanks @bbatsov,

How about a configuration option like this one:

**config/default.yml**:

```
AllowGemfileRubyComment: false
```

**Comment by cetinajero** [comment]
All done 👍 

- [x] Branch rebased to `master` tip
- [x] Added `AllowGemfileRubyComment ` config option disabled by default
- [x] Updated test cases with new config option
- [x] Added documentation
- [x] All CI checks passing

If anything seems wrong or something has to be changed, please let me know.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
