### PR TITLE
CI against Ruby 2.7

### PR DESCRIPTION
**Pull request by koic**
Ruby 2.7.0 has been released and this Ruby version is available on `circleci/ruby:2.7` image.

- https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
- https://hub.docker.com/r/circleci/ruby/tags/

```console
% docker pull circleci/ruby:2.7
2.7: Pulling from circleci/ruby

(snip)

Status: Downloaded newer image for circleci/ruby:2.7
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
Hmm, `Check requiring libraries successfully` of ruby-2.7-rubocop matrix has been failed because of `require': cannot load such file -- parser (LoadError)`.

```console
$ #!/bin/bash -eo pipefail
ruby -I lib -r rubocop -e 'exit 0'
Traceback (most recent call last):
	4: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /home/circleci/project/lib/rubocop.rb:3:in `<top (required)>'
	1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- parser (LoadError)

Exited with code exit status 1
```

https://circleci.com/gh/rubocop-hq/rubocop/79263

**Comment by bbatsov** [comment]
@koic Is there a Parser release compatible with Ruby 2.7?

**Comment by buehmann** [comment]
Seems to be related to https://github.com/bundler/bundler/issues/7197

This could be a workaround:
```diff
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 2c41744f2..ade82f946 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,7 +40,7 @@ rubocop_steps: &rubocop_steps
       name: Check requiring libraries successfully
       # See https://github.com/rubocop-hq/rubocop/pull/4523#issuecomment-309136113
       command: |
-        ruby -I lib -r rubocop -e 'exit 0'
+        ruby -I lib -r bundler/setup -r rubocop -e 'exit 0'
 
 jobs:
 
```

**Comment by koic** [comment]
Thanks for the advices! Parser gem seems to be compatible with Ruby 2.7. I added a workaround based on @buehmann's advice. ruby-2.7-rubocop matrix has been passed!

**Comment by bbatsov** [comment]
Thanks!

**Comment by koic** [comment]
Thanks too! I added Ruby 2.7 matrix to required status checks to pass before merging on this GitHub repo.

**Pull request merged**
