### PR TITLE
Document support for frozen_string_literal: false

### PR DESCRIPTION
**Pull request by gfyoung**
xref #7426

### CODE REVIEW

**Comment by gfyoung** [comment]
This is my first time contributing to the `rubocop` project, so I have a question about commit messages.  My PR is not "fixing" the issue (it's a two-parter, and this only addresses one part of it), so I wasn't sure that I needed to add a "fix" prefix to my commit message.

Let me know what makes sense here!

**Comment by bbatsov** [comment]
The comment seems a bit confusing to me. Shouldn't it say that RuboCop will ignore files where the  the comment exists and is set to `false` instead?

**Comment by gfyoung** [comment]
> The comment seems a bit confusing to me. Shouldn't it say that RuboCop will ignore files where the the comment exists and is set to false instead?

@bbatsov : We can write it like that as well.  I just want to make it clear that users have an alternative if they have the cop turned on.

**Comment by gfyoung** [comment]
@bbatsov : I've updated the wording and included an example.  Have a look.

**Comment by bbatsov** [comment]
Looks good to me. Thanks!

**Pull request merged**
