### PR TITLE
[FIX #5718] Enable rspec with appveyor

### LINKED ISSUE #5718: [Suggestion] Appveyor Rspec test reporter
Just wanted to mention that the `appveyor-worker` gem now support RSpec in addition to Minitest for it's test reporting. It allows the execute tests to appear in the Test summary on Appveyor.

See relate issue: https://github.com/ukoloff/appveyor-worker/issues/1

I've hooked it up with the RuboCop extension I'm working on:
https://github.com/SketchUp/rubocop-sketchup

You can see an example build here:
https://ci.appveyor.com/project/thomthom/rubocop-sketchup

Working fine so far. Just thought I'd mention it in case you wanted to try it out for RuboCop's own Appveyor integration.

To enable it:

Add `gem "appveyor-worker", '~> 0.2` to `Gemfile`.

Then add to `.rspec`

```
--require appveyor/worker
```

### PR DESCRIPTION
**Pull request by amrrbakry**
Closes #5718. Enable Rspec with appveyor

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [X] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by amrrbakry** [comment]
seems like the appveyor build is taking way too long

**Comment by koic** [comment]
Thanks for opening a PR. 

But I'm sorry about I was not aware of the issue #5718 comment.
Appveyor has long runtime of CI, on the other hand it has not detected problems for a long while. 

Therefore, we are considering removing Appveyor from CI matrix.

@bquorning I think RuboCop's CIs will be unified into CircleCI. What do you think about it?

**Comment by koic** [comment]
Thanks for opening a PR. 

But I'm sorry about I was not aware of the issue #5718 comment.
Appveyor has long runtime of CI, on the other hand it has not detected problems for a long while. 

Therefore, we are considering removing Appveyor from CI matrix.

@bquorning I think RuboCop's CIs will be unified into CircleCI. What do you think about it?

**Comment by koic** [comment]
Thanks for opening a PR. 

But I'm sorry about I was not aware of the issue #5718 comment.
Appveyor has long runtime of CI, on the other hand it has not detected problems for a long while. 

Therefore, we are considering removing Appveyor from CI matrix.

@bquorning I think RuboCop's CIs will be unified into CircleCI. What do you think about it?

**Comment by koic** [comment]
Thanks for opening a PR. 

But I'm sorry about I was not aware of the issue #5718 comment.
Appveyor has long runtime of CI, on the other hand it has not detected problems for a long while. 

Therefore, we are considering removing Appveyor from CI matrix.

@bquorning I think RuboCop's CIs will be unified into CircleCI. What do you think about it?

**Comment by koic** [comment]
Thanks for opening a PR. 

But I'm sorry about I was not aware of the issue #5718 comment.
Appveyor has long runtime of CI, on the other hand it has not detected problems for a long while. 

Therefore, we are considering removing Appveyor from CI matrix.

@bquorning I think RuboCop's CIs will be unified into CircleCI. What do you think about it?

**Comment by bquorning** [comment]
> @bquorning I think RuboCop's CIs will be unified into CircleCI. What do you think about it?

I haven’t heard of CircleCI having any plans to offer Windows support.

I believe there was a discussion about whether Appveyor should be dropped from the build matrix, but we decided to keep it but not mark it as required (as to not block “fast” PRs).

> Enable rspec with appveyor

I am not sure I understand the purpose of this PR. Doesn’t RSpec already run on Appveyor? See e.g. https://github.com/rubocop-hq/rubocop/blob/014639fee08d20f4c431c7152417c924ab3960eb/appveyor.yml#L15-L17

**Comment by amrrbakry** [comment]
@bquorning nope, appveyor didn't report rspec tests until recently. see https://github.com/ukoloff/appveyor-worker/issues/1

**Comment by bquorning** [comment]
Here is a two month old build from Appveyor, rspec seems to have run just fine: https://ci.appveyor.com/project/bbatsov/rubocop/builds/18670656/job/ubw4wo1u16wgfj6q

Here is a more recent build, rspec also running fine: https://ci.appveyor.com/project/bbatsov/rubocop/builds/19818955/job/73b7yvyblot7dyqf

Please help me understand what is accomplished by this PR.

**Comment by koic** [comment]
> I haven’t heard of CircleCI having any plans to offer Windows support.

Oops! My explanation was bad :bow:

> I believe there was a discussion about whether Appveyor should be dropped from the build matrix

Indeed. I would have liked to ask about dropping Appveyor from the build matrix.
So If we droped Appveyor from the matrix, I thought that this change would not be merged.

**Pull request closed without merging**
