### PR TITLE
Tweak Lint/MissingSuper [See #8376]

### PR DESCRIPTION
**Pull request by marcandre**

### CODE REVIEW

**Comment by ruanltbg** [comment]
Thank you for the hard/fast work.

**Comment by fatkodima** [comment]
Seems like there are another 3 ones https://ruby-doc.org/core-2.7.1/BasicObject.html#method-i-singleton_method_added
Sorry, forgot about them also.

**Comment by marcandre** [comment]
> Seems like there are another 3 ones https://ruby-doc.org/core-2.7.1/BasicObject.html#method-i-singleton_method_added

I never realize those existed. I can't think of a reason for their existence either, as `def singleton_class.method_added` should have the same effect. I added them to the list 👍

**Comment by bbatsov** [comment]
Indeed!

**Pull request merged**
