### PR TITLE
Fix command flags formatting

### PR DESCRIPTION
**Pull request by krzysiek1507**
Fix command flags formatting in basic usage docs.

Before:
Screenshot 2020-06-12 at 12 14 13

After:
Screenshot 2020-06-12 at 12 14 23

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by krzysiek1507** [comment]
Sorry for flooding CI. I should have added `[skip ci]` to the commit. :(

**Comment by bbatsov** [comment]
No worries! Thanks for fixing this!

**Comment by koic** [comment]
Yeah, CI has some cases of checking documentation. So no problem. Thank you!

**Comment by krzysiek1507** [comment]
You're welcome! I'm glad I could help.

**Pull request merged**
