### PR TITLE
[Fix #7331] Add 'forbidden' option to Style/ModuleFunction cop.

### LINKED ISSUE #7331: "none" option for Style/ModuleFunction
## Is your feature request related to a problem? Please describe.

We have found both `extend self` and `module_function` to be problematic for various reasons:
- it leads to subtle bugs in static analysis tools (such as [sorbet](https://github.com/sorbet/sorbet/issues/22) and [yard](https://github.com/lsegal/yard/issues/378))
- in leads to an inconsistent API, where we would prefer opinionated code. For instance, rubocop uses `module_function` within `Util`. Callers often arbitrarily pick one, for instance `Alignment` chose the instance method invocation `begins_its_line?`:
https://github.com/rubocop-hq/rubocop/blob/87ce6e05e7583820ad66cbcb4d84615ed108fba2/lib/rubocop/cop/mixin/alignment.rb#L51
while `HashAlignment` used the class method invocation `Util.begins_its_line?`:
https://github.com/rubocop-hq/rubocop/blob/87ce6e05e7583820ad66cbcb4d84615ed108fba2/lib/rubocop/cop/mixin/hash_alignment.rb#L21

## Describe the solution you'd like

`Style/ModuleFunction` supports two styles, `module_function` (default) and `extend_self`. I would like an additional style, which prohibits both, i would suggest calling this `none`.

## Describe alternatives you've considered

We could write a custom cop instead, but it seems more natural to fold it into `Style/ModuleFunction`.

### PR DESCRIPTION
**Pull request by weh**
Add the option `forbidden` to the Style/ModuleFunction cop.

-----------------

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm OK with the proposed solution overall, but I find the suggest name to be quite confusing. Something like `forbidden`/`not_allowed` might be better IMO.

**Comment by weh** [comment]
you mean the option name 'none'? i can check the other cop config options and choose a better one :)

**Comment by bbatsov** [comment]
Yeah, I was referring to the name of the style.

**Comment by weh** [comment]
cleaned up the mess of rebase and squash. think it should be ok now.

**Comment by weh** [comment]
@bbatsov was the circleci fail just a coincidence?

**Comment by weh** [comment]
rebased and ready to merge :)

**Comment by weh** [comment]
This should be ready to merge @koic

**Comment by weh** [comment]
ping @bbatsov :)

**Comment by bbatsov** [comment]
@weh Sorry about the radio silence. I think you should also expand the cop description a bit (I mean the summary sentence). Right now the description of the cop doesn't quite reflect it's actually capabilities. You'll also have to update on top of `master` and move the changelog entry accordingly.

**Pull request merged**
