### PR TITLE
Extend cops meta data

### PR DESCRIPTION
**Pull request by Darhazer**
* Merged default.yml, enabled.yml, and disabled.yml into single config
* Added version added/changed/removed for all cops since 0.5 (428/428 cops)

TODO:
* [x] Update documentation generating script to include meta info
* [x] Add Safe & SafeAutocorrect meta-data (currently 6 cops are marked unsafe, 10 with unsafe autocorrect, probably needs more work)
* [x] Add version meta data for older releases 
* [ ] ~Update OBSOLETE_COPS checks to check VersionRemoved meta data~ We don't have VersionRemoved in this release, this should be a follow up for 1.0
* [x] Update manual/configuration.md
* [x] Review EnabledByDefault/DisabledByDefault option

I wonder what should we do with removed cops? Add them in a separate config? Leave them in default.yml in alphabetical order? Just remove them and start providing the VersionRemoved from 1.0 onwards?

Currently they are in a separate file, not required in default.yml, as otherwise config loader breaks.

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
> I wonder what should we do with removed cops? Add them in a separate config? Leave them in default.yml in alphabetical order? Just remove them and start providing the VersionRemoved from 1.0 onwards?

I think we should remove them and start providing VersionRemoved after your PR is merged for cops deleted in the future. 

My plan for them down the road is to just leave dummy classes in place, so we can keep the cops in the default file and don't need any special handling for them.

**Comment by bbatsov** [comment]
P.S. Great progress, btw! The PR is shaping up pretty well!

**Comment by Darhazer** [comment]
I processed all cops down to version 0.5 - seems we don't keep a changelog for earlier releases, so now the true archeology begins ;) Only 36 cops ways for their version meta data.

Also, I've updated the documentation generation.

@rubocop-hq/rubocop-core if someone wants to update the instructions in manual/configuration.md and how EnabledByDefault/DisabledByDefault works, feel free to contribute to the PR while I'm tackling the Safe options and digging the latest version meta data

**Comment by bquorning** [comment]
What does `VersionChanged` mean? Would it be possible for a cop to be “changed” twice, and can `VersionChanged` be an array of values?

**Comment by Darhazer** [comment]
> What does VersionChanged mean? Would it be possible for a cop to be “changed” twice, and can VersionChanged be an array of values?

We keep only the latest version in which the cop was changed. VersionChanged means anything that affects configuration, including adding or removing a configuration option and changing default values. Adding or removing auto-correct support also counts, as this allows/disallows using AutoCorrect in the configuration

**Comment by bbatsov** [comment]
> I processed all cops down to version 0.5 - seems we don't keep a changelog for earlier releases, so now the true archeology begins ;) Only 36 cops ways for their version meta data.

That's fine. We can fill in the missing data later. 

> @rubocop-hq/rubocop-core if someone wants to update the instructions in manual/configuration.md and how EnabledByDefault/DisabledByDefault works, feel free to contribute to the PR while I'm tackling the Safe options and digging the latest version meta data

For the safe metadata - feel free to just set everything to safe and we can just tweak this later. There are some well-known examples of unsafe cops and unsafe autocorrects and you should certainly mark those, but I don't want you to spend too much time checking each cop. I think it's perfectly fine to set the correct metadata gradually.

**Comment by bbatsov** [comment]
>  Review EnabledByDefault/DisabledByDefault option

Btw, review in what sense? I'm guessing we can leave this more or less the same and add something similar for cops with status "New" down the road.

**Comment by bquorning** [comment]
How will a developer use these new `VersionAdded`/`VersionChanged`/`VersionRemoved` keys? When adding/changing a cop, I won’t necessarily know in which version it will be released.

**Comment by bbatsov** [comment]
@bquorning Well, that's always the next release (optimistically), so I think it's pretty easy to guess. Obviously those are going to adjusted around merge time if needed. I'm not concerned about that at all, as I've been using a very similar scheme on other projects and the getting the version numbers right was never a practical problem. 

As for the general usage - see #5978 and the related tickets. That's the biggest milestone on the road to 1.0, together with the extraction of `rubocop-performance` and `rubocop-rails`.

**Comment by Darhazer** [comment]
I rebased on master, adding 0.59.2 to the VersionChanged meta-data, completed the rest of the TODO points, squashed commits, and separated the automatic generated manual in a separate commit for easier reviewing.

Guess it's ready for review and merge.

**Comment by bbatsov** [comment]
Amazing work! 🙇 ❤️ 💯 

Now on to using the metadata for great good! (#5979)

**Pull request merged**
