### PR TITLE
Remove `save_screenshot` from `Lint/Debugger` (revival)

### PR DESCRIPTION
**Pull request by ybiquitous**
This PR is a revival of PR #7853. Please see the PR #7853 description for details.

Closes #7853

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by marcandre** [comment]
Not sure what's up with circleci. I'll merge nevertheless as changes are fine

**Comment by bbatsov** [comment]
And we still have to make this configurable at some point. :-)

**Comment by ybiquitous** [comment]
It seems good to add `AllowedMethods` option to `Lint/Debugger` like `Lint/RedundantSafeNavigation`:

https://github.com/rubocop-hq/rubocop/blob/25c22bc3efed74092d26cadef75447f646cbbf2d/config/default.yml#L1762-L1773

**Comment by bbatsov** [comment]
@ybiquitous Yeah, exactly.

**Comment by ybiquitous** [comment]
@bbatsov I've opened a new issue #8927. 👌

**Pull request merged**
