### PR TITLE
Change the max line length of `Layout/LineLength` to 120

### PR DESCRIPTION
**Pull request by koic**
This PR changes the max line length of `Layout/LineLength` from 80 to 120 based on #7833 survey.

Cc @rubocop-hq/rubocop-core 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks!

**Comment by andyw8** [comment]
Have the survey results been published?

**Comment by AlexWayfer** [comment]
> Have the survey results been published?

https://metaredux.com/posts/2020/05/26/rubocop-defaults-survey-results.html

**Comment by AlexWayfer** [comment]
@koic I guess, you forgot about description: https://github.com/koic/rubocop/blob/9408f1fed81a5a7d2ed68e7f70f726d6c6a1be45/config/default.yml#L860-L861

**Comment by bbatsov** [comment]
Yeah, I updated this a few days later.

**Pull request merged**
