### PR TITLE
Add empty line after guard clause on docs

### PR DESCRIPTION
**Pull request by felipecabargas**
"Good" example would throw another exception regarding the need of an empty line after a guard clause.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by marcandre** [comment]
LGTM. Why is this PR a draft?

**Comment by felipecabargas** [comment]
@marcandre Doc tests failed so I need to check those

**Comment by marcandre** [comment]
> @marcandre Doc tests failed so I need to check those

Nice of you :-)  No need though, we can see this.

You want to modify the cop's documentation directly (and then sync with `rake generate_cops_documentation`, but you've already done that part manually)

**Comment by felipecabargas** [comment]
Marked ready for review then @marcandre

**Comment by koic** [comment]
Thanks!

**Pull request merged**
