### PR TITLE
Fix NodePattern raising errors on some inputs

### LINKED ISSUE #5470: NodePattern fails extracting node types when presented with nil
### Ruby Code:
A short test case for this problem:
```ruby
pattern = RuboCop::NodePattern.new('(send ($send ...) _method)')
source = 'a' # "(send nil :a)"
node = RuboCop::ProcessedSource.new(source, RUBY_VERSION.to_f, nil).ast
type = pattern.match(node)
```
#### Expected behavior

`pattern.match(node)` returns `nil`

#### Actual behavior

`pattern.match(node)` raises:

```
NoMethodError: undefined method `type' for nil:NilClass
```

### Test variant that works:
```ruby
pattern = RuboCop::NodePattern.new('(send $(send ...) _method)')
source = 'a' # "(send nil :a)"
node = RuboCop::ProcessedSource.new(source, RUBY_VERSION.to_f, nil).ast
result = pattern.match(node)
type = result&.type
```

#### Why this is relevant:

I'm trying to write a `NodePattern` that captures the difference between a `send` and `csend`.

#### Workaround:
For now, I can avoid this problem by:
* Specifying `RuboCop::NodePattern.new('(send $({send csend} ...) _method)')` instead of `RuboCop::NodePattern.new('(send (${send csend} ...) _method)')`
* Extracting the node's type based on `result.type`

## RuboCop version

```
$ bundle exec rubocop -V
0.49.1 (using Parser 2.4.0.2, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by marcandre**
This fixes #5470 

Note: the first two commits are not directly related, but make things a bit easier to debug.

### CODE REVIEW

**Comment by Drenmi** [comment]
If you're hungry for more, there's a long standing request to add an "any child" matcher. This would be especially helpful when matching on hashes. Consider:

```
ruby-parse -e '{ foo: 1, bar: 2 }'

(hash
  (pair
    (sym :foo)
    (int 1))
  (pair
    (sym :bar)
    (int 2)))
```

We may be interested in hashes that have a `foo: 1` pair, but the pairs can appear in any order, so we can't reliably match that in a pattern. 🙂 

What is needed is a suggested extension to the syntax, and the actual implementation.

**Comment by marcandre** [comment]
@Drenmi  Is there an issue already open for this? Doesn't seem very hard to do...

**Comment by Drenmi** [comment]
@marcandre I don't think there's an issue, but feel free to open one. 🙂

**Comment by marcandre** [comment]
> @marcandre I don't think there's an issue, but feel free to open one. 🙂

Created #6841

**Pull request merged**
