### PR TITLE
Added Prettier and a .prettierrc to auto-format YAML now, and Ruby in the future

### PR DESCRIPTION
**Pull request by ndbroadbent**
I've started using the `formatOnSave` option in VS Code with [Prettier](https://prettier.io/), and it's amazing. I feel so much more productive. It's especially useful for open-source projects. Prettier enforces a consistent style, so you don't have to think about code formatting in PRs.

I noticed that Prettier was fixing a few things in the YAML files, so I've set up a `.prettierrc` configuration file that tries to match the current format (single quotes, and tab width: 2.) Although the YAML files were actually a bit inconsistent, and used different styles in different places. I also ran it on the existing YML files with: `prettier --write *.yml **/*.yml`. (I've added a `./bin/format` command that people can run before sending PRs.)

Prettier actually caught a duplicate key error in `config/default.yml`:

```
$ ./bin/format
appveyor.yml 78ms
mkdocs.yml 24ms
readthedocs.yml 10ms
config/default.yml
[error] config/default.yml: SyntaxError: Map keys must be unique; "VersionChanged" is repeated (3877:3)
```

(`Style/SafeNavigation` had a duplicate `VersionChanged` key.)

I've also added a minimal `package.json` and `yarn.lock` so that people can run `yarn install` to install the right version of Prettier.

It's also worth mentioning that [`prettier-ruby`](https://github.com/iamsolankiamit/prettier-ruby) is being developed, so we might be able to auto-format Ruby code in the future. This will pair really nicely with RuboCop, just like Prettier + eslint. Prettier can auto-format the code, and then RuboCop will handle the code linting with cops. When `prettier-ruby` is stable and ready for production, the `./bin/format` command can be updated to format all the Ruby files as well.

(I know it's a bit weird to add a JavaScript tool to a Ruby project, but it works really well and has a huge community.)

Note: I've opened [a similar PR for `rubocop-rails`](https://github.com/rubocop-hq/rubocop-rails/pull/18).

### CODE REVIEW

**Comment by ndbroadbent** [comment]
Related issue where people discuss Prettier for Ruby: https://github.com/rubocop-hq/rubocop/issues/4951

**Comment by bbatsov** [comment]
Well, there's also `rubocop --fix-layout`, which is obviously our preference when it comes to a code formatting tool. :-)

**Comment by ndbroadbent** [comment]
@bbatsov Oh, I was under the impression that `rubocop --fix-layout` was a bit limited compared to an opinionated code reformatter like Prettier or Rufo. Similar to how `eslint` can do some code formatting, but doesn't have a complete set of heuristics and rules like Prettier.

Or is the goal of RuboCop to eventually be a complete Ruby formatter, on par with Prettier?

**Comment by bbatsov** [comment]
Potentially yes, although that's not a high priority. We are always looking to improve the code formatting abilities of RuboCop. 

Thanks for the suggestion, but that this point I'd skip on using prettier (even if it's only for the yaml).

**Pull request closed without merging**
