### PR TITLE
[Fix #8004] Add formatter for GitHub Actions

### LINKED ISSUE #8004: A new formatter for GitHub Actions
## Is your feature request related to a problem? Please describe.

I have the following workaround to run RuboCop on GitHub Actions and show detected RuboCop issues to a pull request page:

https://gist.github.com/ybiquitous/72a1d7cf0eb9bbb9255d84d1ee904881

I think there are the following problems:

- Regex written in the workaround above is complicated and hard to read and maintain.
- Users who don't know the workaround cannot easily use RuboCop in Actions.

## Describe the solution you'd like

Add a new formatter for GitHub Actions.

## Describe alternatives you've considered

Add a description of the usage on GitHub Actions to the RuboCop documentation.

## Additional context

Here are the GitHub Actions' messaging specs:

- https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message
- https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

RuboCop has more severities than warning and error, so we need to map RuboCop's severities and GitHub Actions' severities. For example:

| RuboCop    | GitHub Actions |
|------------|----------------|
| refactor   | warning        |
| convention | warning        |
| warning    | warning        |
| error      | error          |
| fatal      | error          |

### PR DESCRIPTION
**Pull request by lautis**
Implement a formatter for GitHub Actions. When using this formatter within GitHub Actions, GitHub shows detected RuboCop issues on pull request page as annotations.

The formatter uses `fail_level` to determine which GitHub level to use for each annotation. By default, all RuboCop severities are errors. If fail level is set and severity is below fail level, a warning will be created instead.

Fixes #8004.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The code seems fine to me. The only think remaining is adding some documentation about the new formatter, otherwise it's unlikely that anyone will end up using it. :-)

**Comment by lautis** [comment]
Thank you for reviewing the code. I added documentation to the formatters page.

**Comment by bbatsov** [comment]
> The formatter uses fail_level to determine which GitHub level to use for each annotation. By default, all RuboCop severities are errors. If fail level is set and severity is below fail level, a warning will be created instead.

I'd also add this to the docs.

**Comment by lautis** [comment]
Makes sense, added.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
