### PR TITLE
Update links to rubocop-hq

### PR DESCRIPTION
**Pull request by sunny**
This replaces `https://github.com/bbatsov/rubocop` by `https://github.com/rubocop-hq/rubocop` in the whole project. And that's it.

My thinking was that:
- the latest CHANGELOG entries had differing URLs even though they point to the same repo
- the old links still work but incur a redirect

Hope this is useful!

### CODE REVIEW

**Comment by koic** [comment]
You should also make the following changes so that CHANGELOG does not regress 😉 

```diff
diff --git a/spec/project_spec.rb b/spec/project_spec.rb
index 7f365e0b0..fa7816566 100644
--- a/spec/project_spec.rb
+++ b/spec/project_spec.rb
@@ -144,7 +144,7 @@ RSpec.describe 'RuboCop Project', type: :feature do
         it 'has a valid URL' do
           issues.each do |issue|
             number = issue[:number].gsub(/\D/, '')
-            pattern = %r{^https://github\.com/(bbatsov|rubocop-hq)/rubocop/(?:issues|pull)/#{number}$} # rubocop:disable Metrics/LineLength
+            pattern = %r{^https://github\.com/rubocop-hq/rubocop/(?:issues|pull)/#{number}$} # rubocop:disable Metrics/LineLength
             expect(issue[:url]).to match(pattern)
           end
         end
```

**Comment by koic** [comment]
This looks good. Could you squash your commits into one?

**Comment by sunny** [comment]
Done ! And rebased against master.

**Comment by koic** [comment]
Thanks!

**Comment by sunny** [comment]
Thank you for the swift merge!

**Comment by wilg** [comment]
Has this rename affected the documentation? http://docs.rubocop.org/ does not seem to reflect the new cops listed in the changelog.

**Comment by sunny** [comment]
@wilg I am not sure I understand. This PR was just about removing a redirection, not about renaming anything.

Can you give an example of a cop you do not find in the documentation?

**Pull request merged**
